### ISSUE TITLE
Diff process is not working  for 4 ontologies

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#105]
![Image](https://user-images.githubusercontent.com/29259906/203272421-6a83d54c-c85d-4804-b508-017ba9993139.png)

**Comment by syphax-bouazzouni** [comment]
Still the case, a year after


![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/61425684-426e-4c8e-937a-5592c8eca3fb)

**Comment by jonquet** [comment]
This issue will certainly stay like this untill we plug the new bubastis or work done by Naouel.
I regularly run the diffs manually to get rid of some in this list. 
But considering the use of the diff for the moment (no UI) I would not bother too much

**Comment by syphax-bouazzouni** [comment]
duplicate of https://github.com/agroportal/project-management/issues/311
