### ISSUE TITLE
Le composant O'FAIRe ne s'affiche pas parfois

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#107]
Exemple de PO2: 
http://agroportal.lirmm.fr/ontologies/PO2/?p=summary

<img width="435" alt="image" src="https://user-images.githubusercontent.com/7379183/198554746-cca55d7f-8aaa-4c5f-bffc-4fe12f9c000d.png">

Je n'ai pas vu d'autres occurence de ce bug.

**Comment by syphax-bouazzouni** [comment]
A knowen issue, related to https://github.com/ncbo/bioportal_web_ui/issues/179

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/724ba80dcde3f28b8a0a770a59d26450520ee0e4
