### ISSUE TITLE
Give users indications of what are the mappings types

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#118]
### Requirements 

- [ ] Add a documentation page of the different mappings types
- [ ] Add tooltip information in the UI when hovering each of the mapping types

![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/ffb6ccc9-c96e-47f4-be33-950f997d99eb)

**Comment by jonquet** [comment]
To be refined when @Bilelkihal will re-fresh the UI of this page.

**Comment by jonquet** [comment]
Pour la documentation de internal/ external je propose un (i) proche de type qui dit: 
_Mappings are from one ontology in 'AgroPortal': to another 'AgroPortal' ontology (internal); to an ontology not in AgroPortal (external); to an ontology stored in another OntoPortal instance (inter-portal)._ 

Pour l'UI, je propose: 
- D'enlever la colonne Actions, comme deja discuté dans d'autres tableaux. Mettre un stylo et une poubelle plutôt.

**Comment by syphax-bouazzouni** [comment]
Possible task for you @galviset to do with this https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/687

**Comment by jonquet** [comment]
Adding a new screenshot of the new design to see the limitation. 

<img width="685" alt="Capture d’écran 2024-09-29 à 18 24 36" src="https://github.com/user-attachments/assets/37d2fee3-8aa4-44f4-b18b-44b9f834636d">

- [ ] Replace Actions words by classic icons
- [ ] Chose 3 icons for "internal", "interportal" and "external" and explain 
- [ ] For the source (which can be a string coming from the mapping itself I recommend also an icon approach) we need 4 icons for the 4 following types : LOOM, SAME_URI, CUI and REST
- [ ] Mouse over on the 4 icons shall display an explanation
- [ ] Explain all icons (all of them) in a legend similar to the ones poping-up on the (i) on the Mapping page (https://agroportal.lirmm.fr/mappings). Put the (i) aside "Create New Mapping"

Explanations for the 3 types of mappings can be taken from: 
- https://hal-lirmm.ccsd.cnrs.fr/lirmm-01395880 => for English
- https://hal-lirmm.ccsd.cnrs.fr/lirmm-01395900 => for French

Explanations for the multiple source of mappings can be taken from: 
https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/mappings-JYGyUrAJkw

Explanations need to be in the local language file for FR and EN minimum.

**Comment by jonquet** [comment]
> Possible task for you @galviset to do with this #687
@galviset indeed this is a good exercise tell us ?

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/798
