### ISSUE TITLE
Update Login & Register views design

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#130]
**Why should we update the existing views:**
- The old interface has bad styling and does not keep pace with modern website designs.

**Decisions I made in the new design that need to be approved:**
- Replace "Account name" by "User name" (Because it is the most used in different websites).
- Add registration and login directly using Google and GitHub (make the process much easier for users, users do not like to remember a lot of passwords, more secure, the internet is going passwordless in the next years).
- Real-time user error correction in registration (Ex: Tell the user that the username is already in use, or that the password is weak the time he's typing).

Check the new design & leave me comments in Figma:
https://www.figma.com/file/n2tOIfgVlVvFAr3F00Ab5m/Ontoportal-alliance?node-id=9%3A19&t=BhpXNbL45EpcQHv2-1

**Comment by Bilelkihal** [comment]
I've replied to your comments in Figma.
Yeah, anyone with the link can view it,
do I make it private?

**Comment by syphax-bouazzouni** [comment]
@jonquet Can you review and validate the [Figma mockup](https://www.figma.com/file/n2tOIfgVlVvFAr3F00Ab5m/Ontoportal-alliance?node-id=9%3A19&t=BhpXNbL45EpcQHv2-1) so that we can start implementation

**Comment by jonquet** [comment]
Figma mockups looks great. Just made 2 comments. 

Is the integration with Google / GitHub login easy to do? This would be a great addition. 
See also: https://github.com/agroportal/project-management/issues/341
(i.e., even if a user do not select login via GitHub, it woudl be good to ask them their ids on GitHub and ORCID)

Ready to start implementing.

**Comment by syphax-bouazzouni** [comment]
Done in #142 and #144 


![Image](https://user-images.githubusercontent.com/29259906/219620782-1b0d5e87-bc0e-404c-8221-bc0de58ee565.png)



![Image](https://user-images.githubusercontent.com/29259906/219620838-42245486-a023-4ce4-a586-d357bfa31440.png)
