### ISSUE TITLE
Update feedback page design

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#151]
**Problems:**
- The old interface has bad styling and does not provide a good user experience.

**Changes I made:**
- Use a modern design style.
- Add a text field for the Error/proposition page URL (This field gonna be by default filled with the URL of the page which the user clicks on feedback on, but he has the possibility to edit it)
- Add the possibility for the user to select tags like (Bug, question, or proposition ...)

Check the new design & leave me comments on [Figma mockup](https://www.figma.com/file/n2tOIfgVlVvFAr3F00Ab5m/Ontoportal-alliance?node-id=9%3A19&t=xH3UpSxlzFLEdMv4-1)

**Comment by syphax-bouazzouni** [comment]
Implemented in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/156 and https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/201 



![Image](https://user-images.githubusercontent.com/29259906/219620548-ba009224-1172-46b3-8986-27222ce63deb.png)
