### ISSUE TITLE
Error when submitting a new ontology submission

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#154]
Since last release or recently loading a new ontology and th efirst submission returns a "Something went wrong" page, while the ontology file is well loaded and processed. 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/7379183/212280201-65fb1d88-9d94-44c6-b5dd-d2ad94283378.png">

I have reproduced the error on StagePortal and AgroPortal. 
Tried with a private ontology and public one.
Test at 9:55 am on Friday 13th jan 2023  
https://stageportal.lirmm.fr/ontologies/MO/
https://agroportal.lirmm.fr/ontologies/MO/
Test on Thursday
https://agroportal.lirmm.fr/ontologies/AWS

**Comment by syphax-bouazzouni** [comment]
```
ArgumentError (comparison of String with 400 failed):
  
app/controllers/application_controller.rb:226:in `<'
app/controllers/application_controller.rb:226:in `response_success?'
app/controllers/application_controller.rb:230:in `response_error?'
app/controllers/submissions_controller.rb:46:in `create'
```

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/155
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/29259906/212297037-fcd97a3d-cdd8-45b3-8d7e-cb097ac508e3.png">

**Comment by syphax-bouazzouni** [comment]
But errors message are not well displayed
<img width="897" alt="image" src="https://user-images.githubusercontent.com/29259906/212344834-597e6ef2-af05-492f-b2e6-b389165c9dbf.png">

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/2f76ebd9026dc3c04cefee373222ba36b1a5c4fe

![Image](https://user-images.githubusercontent.com/29259906/212773393-1e58caaf-a635-4eed-8192-898582dca5a1.png)
