### ISSUE TITLE
Update and simplify the submission workflows  (creation, edition, curation, deletion)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#161]
## Issues

- An ontology admin can't delete or edit a specific submission 
- On the submission creation a user gets a form with too many fields to fill and that we are extracted anyway 
- The user doesn't have his ontology process feedback/follow-up
- If the process fails the user is not informed of the issues
- The submission form is big and hard to find a specific field to fix/fill 

## Requirements 

Below is the ideal workflow that will tend to achieve in the future 

### 1- Creation

- [x] #162
- [ ]  Inform the user of what we do behind the scene (real-time follow-up of the ontology process) (see https://www.youtube.com/watch?v=fqYoLWKjQWE)
- [ ]  Notify the user of the success or failure of the process
- [ ]  If successful show tells the user to curate their metadata if needed and give them a report of their metadata (list the extracted ones, and the empty ones)
- [ ]  If failure show them simplified logs (like protégé see https://github.com/agroportal/project-management/issues/320)

### 2 - Edition & Curation 

- [x]  Show the full submission form with a filter to help the curation (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/136)
- [x]  Portal Admin curation tool (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/138)

### Deletion

- [x]  Give the user possibility to remove submissions if wanted  (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/139)

**Comment by syphax-bouazzouni** [comment]
@jonquet can you try this new workflow, by creating an ontology and tell me your remarks

**Comment by jonquet** [comment]
Tested on StagePortal. 
- I would by default subscribe the person creating the ontology to the notifications for this ontology.
- I like the mandatory property only. 
- I would add right now a sentence explaining on the submission creation page "We are only displaying the mandatory metadata properties here. We will automatically extract from the ontology source file additionnal metadata properties (if available) and invited you back to validate and complete the extraction afterwards."
- On the notification of parsing email I would change the text to complte with : 
"Class metrics calculated 
 _FAIRness assessment results will be only available tomorrow._
Please contact [sifrportal-support@lirmm.fr](mailto:sifrportal-support@lirmm.fr) if you have questions. 

The ontology can be [browsed in Stageportal](http://stageportal.lirmm.fr/ontologies/UC_SENSE).
_You can now validate the metadata extracted form the source file and complete them by "Editing" the current submission. 

In the future, you can create new submissions (e.g., a new significant version) by "Adding" submission._
"

- On the ontology summary page I would move the button "Edit" from where it is to the place where the text edit is now. A repeat the button for each line. It will reduce the confusion betweem edition and addition. 

<img width="162" alt="image" src="https://user-images.githubusercontent.com/7379183/214283611-538ac09b-717a-4d2b-8073-7502a8ce8979.png">

Move it to 
<img width="79" alt="image" src="https://user-images.githubusercontent.com/7379183/214283859-09e270e8-01d5-46d6-b754-229dd556cfe2.png">

**Comment by syphax-bouazzouni** [comment]
Done in  https://github.com/ontoportal-lirmm/bioportal_web_ui/releases/tag/v2.7.0

But work still needs to be done, on the curation side, to help and guide users, to complete and correct their metadata.
