### ISSUE TITLE
Creating a note on  one ontology multiply it by 4 (on StagePortal)

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#167]
One notre created => 4 notes created 

Tested on StagePortal UC_SENSE: https://stageportal.lirmm.fr/ontologies/UC_SENSE

<img width="650" alt="image" src="https://user-images.githubusercontent.com/7379183/214284354-789d5ba7-d9c3-4f03-828c-f44a111b610a.png">

**Comment by syphax-bouazzouni** [comment]
this is related to migration to Hotwire, which does that old code initialized several times (the event of adding note)

related to
