### ISSUE TITLE
Remove duplication of status and version on the Ann and Edit submission page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#168]
Pour une raison onconnue nous avons 2 propriétés qui sont la d2 fosi sur la page Add et Edit Submisison 

Version et status.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/7379183/214813506-2baff859-4bcd-44f6-a1e1-4dd255f3c148.png">

Il faut enlever les duplicats et s'assurer que le changement est bien effectif quand le chap est utilisé. 

Voir https://github.com/agroportal/project-management/issues/357

**Comment by syphax-bouazzouni** [comment]
This was fixed in the stageportal and will be deployed in the next release, when it will be more stable/tested

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/29259906/214870950-1c95775c-3a52-460c-aa27-fd42b66a0f03.png">
