### ISSUE TITLE
Metadata values include "none" instead of only restricted values sur la page Edit Submission

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#179]
Apres les changements recents on a: 

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/7379183/216346937-b8488076-12fd-4767-9959-eb2bfddc36de.png">
Il faut enlever "non" qui casse la regle du boolean. 

Idem sur format... pas besoin du none

<img width="277" alt="image" src="https://user-images.githubusercontent.com/7379183/216347206-ba5ad43a-a882-43b9-8924-7d8b7e76e3f6.png">

**Comment by syphax-bouazzouni** [comment]
None option was removed of all the select attributes
