### ISSUE TITLE
Rafraichir automatiquement les valeurs d'une table apres l'edition de métadonnées en bulk

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#180]
Apres avoir éditer des métadonnées en bulk sur l'interface "Metadata Administration" ce serait bien que la table deja chargée (a partir de laquelle ona observé des problèmes de métadonnées) soit automatiquement rafraichie pour afficher les derniers changements.

**Comment by syphax-bouazzouni** [comment]
related https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/191

**Comment by syphax-bouazzouni** [comment]
Done
