### ISSUE TITLE
Fonctionalities : "clear selection" & "select from list" are not working 

### ISSUE THREAD

**Issue by hibadjebabria169** [ontoportal-lirmm/bioportal_web_ui#189]

**Comment by syphax-bouazzouni** [comment]
fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/bc452d1066a01de323c6c7f8f778a3654fb08380


![Image](https://user-images.githubusercontent.com/29259906/218715111-cc395c69-eb73-4248-a622-487141de2227.png)
