### ISSUE TITLE
Selecting all ontologies should not be invloved through leaving the blank 

### ISSUE THREAD

**Issue by hibadjebabria169** [ontoportal-lirmm/bioportal_web_ui#190]
It's ambiguous when a blank engenders the selection of all ontologies in the list, it's better to do a checkbutton (or similar button) to indicate that

**Comment by jonquet** [comment]
Je ne comprends pas du tout cette issue. Est-ce que @hibadjebabria169 tu peux la préciser ?

**Comment by syphax-bouazzouni** [comment]
The placeholder indicates that if left blank all the ontologies will be fetched 


![Image](https://user-images.githubusercontent.com/29259906/218715792-9fc6213b-3aac-4d41-a78f-099c33784cca.png)

 Adding a specific button (to check button) will add a no necessary action to the users
