### ISSUE TITLE
Sart bulk edit : ambiguity in use

### ISSUE THREAD

**Issue by hibadjebabria169** [ontoportal-lirmm/bioportal_web_ui#191]
Here, as an external user, it is not clear how to use this feature: select the columns and rows to start curating the picked items. 
We can add an explanation on the UI or remove it since we can do the same thing throughout the table itself with the addition of "apply to all".

**Comment by syphax-bouazzouni** [comment]
Technically it will be hard to remove the Sart bulk edit popup and do it directly in the table (for now). But added a help text beside the button 
<img width="446" alt="image" src="https://user-images.githubusercontent.com/29259906/218692122-8dc92ff4-6c87-4bd2-a7c8-1aed3ab939bd.png">

I let this issue open for next iterations

**Comment by syphax-bouazzouni** [comment]
The button was removed, as not used and was complex to maintain.
