### ISSUE TITLE
Remove the minutes and seconds from the dates 

### ISSUE THREAD

**Issue by hibadjebabria169** [ontoportal-lirmm/bioportal_web_ui#194]

**Comment by hibadjebabria169** [comment]
- For date inputs : identify those for which there is no calendar.... it should be registered by the validator date

**Comment by syphax-bouazzouni** [comment]
Resolved with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/242, implementing this component: https://testportal.lirmm.fr/lookbook/inspect/date_time_field/default

Will be merged to production when the work on the summary page ends (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/244)
