### ISSUE TITLE
Version metadata display bugs if its something else than a string

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#2]
If someone upload an ontology with 

 <pav:version rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">1.0</pav:version>
The version will be automatically extracted and store as a number. 
Then the ontology summary page does not display  with error : 
 FATAL -- : ActionView::Template::Error (undefined method `length' for 1.0:Float):

The version needs to be casted to a string.

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/163
