### ISSUE TITLE
Make the list of properties field in the submission form and the metadata administration includes all the properties listed in the `submission_metadata` endpoint.

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#200]
The metadata properties selector component, does not include all the properties listed in the `/submission_metadata` API endpoint

<img width="1991" alt="image" src="https://user-images.githubusercontent.com/29259906/219370550-2279e8d5-da6f-4fce-9855-5dcb5f433e57.png">

**Comment by syphax-bouazzouni** [comment]
update the code with this hard coded list 

```ruby 
 [
     :format, format_equivalent],
     :version,
      :status,
      [:location, location_equivalent],
      :URI,
      :deprecated,
      :hasOntologySyntax,
      :hasFormalityLevel,
      :isOfType,
      :naturalLanguage,
      :description,
      :homepage,
      :documentation,
      :publication,
      :usedOntologyEngineeringTool,
      :abstract, :notes, :keywords, :alternative, :identifier,
      :knownUsage,
      :designedForOntologyTask,
      :hasDomain,
      :coverage,
      :example,
      :conformsToKnowledgeRepresentationParadigm,
      :usedOntologyEngineeringMethodology,
      :accrualMethod,
      :accrualPeriodicity,
      :accrualPolicy,
      :competencyQuestion,
      :versionIRI,
      :source,
      :isFormatOf,
      :hasFormat,
      :includedInDataCatalog,
      :depiction,
      :logo,
      :associatedMedia,
      :released,
      :modificationDate,
      :valid,
      :curatedOn,
      :publisher,
      :hasLicense,
      :morePermissions,
      :copyrightHolder,
      :contact,
      :hasContributor,
      :hasCreator,
      :audience,
      :toDoList,
      :useGuidelines,
      :repository,
      :bugDatabase,
      :mailingList,
      :award,
      :wasGeneratedBy,
      :wasInvalidatedBy,
      :curatedBy,
      :endorsedBy,
      :fundedBy,
      :translator,
      :useImports,
      :hasPriorVersion,
      :isAlignedTo,
      :ontologyRelatedTo,
      :isBackwardCompatibleWith,
      :isIncompatibleWith,
      :comesFromTheSameDomain,
      :similarTo,
      :explanationEvolution,
      :generalizes,
      :hasDisparateModelling,
      :hasPart,
      :usedBy,
      :workTranslation,
      :translationOfWork,
      :preferredNamespacePrefix,
      :preferredNamespaceUri,
      :keyClasses,
      :endpoint,
      :dataDump,
      :csvDump,
      :openSearchDescription,
      :uriLookupEndpoint,
      :uriRegexPattern,
      :metadataVoc,
      :exampleIdentifier,
      :numberOfClasses,
      :numberOfIndividuals,
      :numberOfProperties,
      :entities,
      :numberOfAxioms
    ]
```

**Comment by syphax-bouazzouni** [comment]
@hibadjebabria169 test and close if done

**Comment by syphax-bouazzouni** [comment]
Also, the `format` and `location`  are somehow special, they include other properties. See below what they includes 

```ruby
  def format_equivalent
    %w[hasOntologyLanguage prefLabelProperty synonymProperty definitionProperty authorProperty obsoleteProperty obsoleteParent]
  end

  def location_equivalent
    %w[summaryOnly pullLocation]
  end
```

**Comment by hibadjebabria169** [comment]
So, here's the properties that i didn't found on the list :

- Acronym 
- Title
- Other identifier ( you have only identifier Uri which is different from other identifier) 
- Access rights ( viewing restrictions )
- Hidden or past name
- Bibliographic reference
- Creation date 
- Submission date 
- Notes ( here you listed only one , and actually we have 2 types of notes …) 
- Evaluation
- Group
- Used in project 
- Analytics 
- ToDo list 
- Example of use 
- Created with 
- Hierarchy property
- Access URL
- Download URL
- SPARQL endpoint
- Is part of
- Specializes
- Has disjunctions with
- Root of obsolete branch
- Root resources
- Changes
- Maximum depth of the hierarchy
- Maximum number of children per class
- Average number of children per class
- Number of classes with a single child
- Number of classes with more than 25 children
- Number of classes with no definition

**Comment by syphax-bouazzouni** [comment]
I can't include ontology metadata properties, like Acronyms, Titles, and Access rights, group, catagories ..., (the ones that are listed here: https://data.stageportal.lirmm.fr/ontology_metadata) 

I can only access the submissions fields for now (and listed here https://data.stageportal.lirmm.fr/submission_metadata)

**Comment by syphax-bouazzouni** [comment]
Done https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/669

**Comment by jonquet** [comment]
Is there an equivalent issue so we can also see/select the metadata attributes of the ontolgy object: 
https://data.agroportal.lirmm.fr/ontology_metadata

**Comment by syphax-bouazzouni** [comment]
> Is there an equivalent issue so we can also see/select the metadata attributes of the ontology object: https://data.agroportal.lirmm.fr/ontology_metadata

this new input can select ontologies and submission properties, or do you mean a selector for only ontology properties?

**Comment by jonquet** [comment]
Ahh ok. Good then.
