### ISSUE TITLE
Crop Ontologies ' contacts 

### ISSUE THREAD

**Issue by hibadjebabria169** [ontoportal-lirmm/bioportal_web_ui#209]
The contacts of the crop ontologies group don't appear on the metadata administration page ( when you filter according to the contacts property) but it works on the summary page of each ontology of this group

**Comment by hibadjebabria169** [comment]
![1](https://user-images.githubusercontent.com/59914426/223089385-b0788ba6-da91-4606-8fc8-2bac5ae371eb.png)

**Comment by syphax-bouazzouni** [comment]
related to https://github.com/ontoportal-lirmm/ontologies_api/issues/22
