### ISSUE TITLE
Edition of the version does not work either in the "Edit submission page" nor in the "Admin metadata" page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#215]
Tested on LEXEAU : https://agroportal.lirmm.fr/ontologies/LEXEAU

Since we remove the 2nd occurence of "version" in the Edit submission page we can't change the version anymore... it's like it's the bad one that have been remove from the UI. 

Admin metadata page although it shows the change does not update the value neither.

**Comment by jonquet** [comment]
For LEXEAU value of submisison 18 should be changed to 1.4.1

**Comment by syphax-bouazzouni** [comment]
Strange behavior, it is not related to the change in the UI.

I tried to do it in ncbo_cron, but it is the same issue it does want to change the version to "1.4.1"

**Comment by syphax-bouazzouni** [comment]
Seems to be fixed 

![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/a30c5010-842c-4d79-99f8-52726bfb4cd8)

I fixed it at that time, by creating a new submission and removing the 18
