### ISSUE TITLE
Bug: Deleting an ontology successful but with visible errors

### ISSUE THREAD

**Issue by RaimiSol** [ontoportal-lirmm/bioportal_web_ui#226]
I need help (low priority) to backtrace the origin of an visible error, see the screenshot:
![jsonparse error at administration console](https://user-images.githubusercontent.com/44089477/228827765-253fe5ff-d16c-46c9-add1-2473002c7f31.png)

**NOTE**: I'm using [Biodivportal](https://github.com/BiodivPortal/ontoportal_web_ui) a slightly modified version of this.

The ontology deletion is successful, see the console output:
> Started DELETE "/admin/ontologies" for 172.21.0.1 at 2023-03-30 10:49:06 +0000
> Cannot render console from 172.21.0.1! Allowed networks: 172.20.0.1, 127.0.0.0/127.255.255.255, ::1
> Processing by AdminController#delete_ontologies as JSON
>   Parameters: {"ontologies"=>"BIOBANK"}
> Completed 200 OK in 1499ms (Views: 0.5ms | ActiveRecord: 0.0ms | Allocations: 19003)

The responsible part in the code: [admin_controller.rb at line 306](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/8148e0b255fea531cd58b7cefa3b4c5aba079f60/app/controllers/admin_controller.rb#L306)

Is someone encountering a similar issue and can give me some hints to solve this?

**Comment by syphax-bouazzouni** [comment]
Hi @RaimiSol thanks for the issue, fixed with this https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/229

The was in the admin_controller, where it returned an error response even if it was a success.
