### ISSUE TITLE
Bug (solved): metadata downloader returning files without content for formats: nquads and jsonld

### ISSUE THREAD

**Issue by RaimiSol** [ontoportal-lirmm/bioportal_web_ui#227]
At the endpoint /ontologies/:acronym the buttons N-Triple and JSON-LD trigger downloads for files with content "undefined". 

I solved the issue by modifying the [line 96 in metadata_downloader_controller.js](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/8148e0b255fea531cd58b7cefa3b4c5aba079f60/app/javascript/controllers/metadata_downloader_controller.js#L96)

Using chrome devtools the problem showing up was that the condition `subJson["URI"]` !== undefined` didn't catched null values
the consequences were:
- missing @ id property of jsonldObject
- error in jsonld.toRDF with message: 'Invalid JSON-LD syntax; \"@ id\" value must a string'

**Comment by syphax-bouazzouni** [comment]
OK, can you please provide us with a PR with your fix?

**Comment by syphax-bouazzouni** [comment]
### To reproduce 

1. Go to https://agroportal.lirmm.fr/ontologies/SIREN
2. Click on the button N-Triple


![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/dfb7dd93-460d-4525-923d-8e8036c3ed9d)

3. See the downloaded file, with only `undefined` written instead for the ontology metadata



![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/b5c7470a-6f75-4712-a453-c157141f1d92)

### Proposed fix 

 See https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/256, @SirineMhedhbi clean and review the code
