### ISSUE TITLE
Bug: annotator unexpected output table

### ISSUE THREAD

**Issue by RaimiSol** [ontoportal-lirmm/bioportal_web_ui#230]
**NOTE**: I'm using [Biodivportal](https://github.com/BiodivPortal/ontoportal_web_ui) a slightly modified version of this.

The first seconds after a given input query to the **annotator** the output seems to be regular, see the screenshot below.

![annotator output table](https://user-images.githubusercontent.com/44089477/229108324-ee1285ac-eb91-4d98-9e4c-757e6fb599b3.png)

After a few seconds and many requests (seen in the network tab) the content of the cells in the class and matched class columns change. The cells are displaying small replicas of the portals-homepage, see the screenshot below.

![annotator output table after a few seconds](https://user-images.githubusercontent.com/44089477/229107513-7ee5cc7f-21a1-4c38-925d-a1c78dffc2af.png)

In a debugging session I noticed the following:
1. At [bp_annotator.js line 645](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/877bf0815873deef1775fc2c93c297868d0ce57f/app/assets/javascripts/bp_annotator.js#L645) the returned class link is: {my-UI-address}/ontologies/ENVO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0036016
2. Trying to access the link returns following error: 
> Processing by OntologiesController#show as HTML
>   Parameters: {"p"=>"classes", "conceptid"=>"http://purl.obolibrary.org/obo/UBERON_0036016", "id"=>"ENVO"}
> Completed 500 Internal Server Error in 97ms (Allocations: 17078)
> NoMethodError (undefined method `escape' for URI:Module):  
> app/controllers/application_controller.rb:476:in `get_class'
> app/controllers/ontologies_controller.rb:152:in `classes'
> app/controllers/ontologies_controller.rb:354:in `show' 
> 
> Extracted source (around line #476):
>           
```
      else
        # if the id is coming from a param, use that to get concept
476     @concept = @ontology.explore.single_class({ full: true }, params[:conceptid])
        if @concept.nil? || @concept.errors
          LOG.add :debug, "Missing class #{@ontology.acronym} / #{params[:conceptid]}"
          not_found("Missing class #{@ontology.acronym} / #{params[:conceptid]}")
```

At this point I got stuck because if I run the following:
```
terminal> docker compose exec web sh -c "irb"
irb> URI.escape("somestring")
```
It runs successfully with a warning: 
```
(irb):2: warning: URI.escape is obsolete
=> "somestring"
```

Regarding my ruby versions:
* local:
docker compose exec web sh -c "ruby -v"
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux-musl]
* appliance:
ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/agroportal/project-management/issues/508
