### ISSUE TITLE
Bug: fair_score requests with fairness disabled

### ISSUE THREAD

**Issue by RaimiSol** [ontoportal-lirmm/bioportal_web_ui#232]
I have globally set:
$FAIRNESS_DISABLED = true

Using the chrome dev tools it can be shown that erroneous requests are made related to fair_score.js.

My estimated reason is:
1. In [application.js:L29](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/877bf0815873deef1775fc2c93c297868d0ce57f/app/assets/javascripts/application.js#L29): `//= require fair_score`
2. In [fair_score.js:L634](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/877bf0815873deef1775fc2c93c297868d0ce57f/app/assets/javascripts/fair_score.js#L634) & [L656](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/877bf0815873deef1775fc2c93c297868d0ce57f/app/assets/javascripts/fair_score.js#L656) & [L678](https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/877bf0815873deef1775fc2c93c297868d0ce57f/app/assets/javascripts/fair_score.js#L678): `jQuery("#fairness_assessment").ready( ... )` and `jQuery("#fair-home").ready( ... )` and `jQuery('#fair-summary').ready( ... )`

According to the [jQuery documentation (.ready)](https://api.jquery.com/ready/) `jQuery("#fairness_assessment").ready` is equivalent to `$( document ).ready` which leads to the unexpected behaviour.

**Comment by syphax-bouazzouni** [comment]
Fixed  in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/335
