### ISSUE TITLE
"Show advanced OWL options" does not show any more in New submission page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#250]
Since the last release apparently the "Show advanced OWL options" does not show any more in New submission page. 

<img width="551" alt="Capture d’écran 2023-05-18 à 09 27 58" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/279ad483-0b7e-4db3-8a0f-063c1ebc1e6d">

**Comment by syphax-bouazzouni** [comment]
When we click on edit submission it shows the inputs  
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/06ade8b9-a346-4e91-9b21-48e40e64cb09)

But not when we create a new submision 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/5b572051-7608-485f-b8d8-76029a0e1f7e)

**Comment by syphax-bouazzouni** [comment]
This bug is still in production, and will not be fixed.
In the next UI release, the new submission form will have them also.


![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/8ada1d89-0145-4887-832b-6a813e6e2fe0)
