### ISSUE TITLE
Probleme d'URL des slices sur la page d'acceuil.

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#264]
Lien vers la collection INRAE depuis l’accueil ne fonctionne pas : depuis https://agroportal.lirmm.fr/, on clique sur Slices 
/ [National research institute for agriculture, food and the environment (inrae)](http://inrae.https//agroportal.lirmm.fr)  —> le lien est incorrect http://inrae.https//agroportal.lirmm.fr

Presents pour toutes les slices.

**Comment by syphax-bouazzouni** [comment]
## To reproduce:

1. Go to https://agroportal.lirmm.fr/
2. Click on one of the slices in the slices section 

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/6901d843-7488-45da-ac9f-71b4ccfde56d)
 
## Cause 

Migration from HTTP to HTTP, we need to update this line https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/master/app/views/home/index.html.haml#L126 (@SirineMhedhbi)
