### ISSUE TITLE
Probleme de certificat avec les slices depuis le passage a HTTPS

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#265]
Pb de certificat sur https://inrae.agroportal.lirmm.fr/

**Comment by syphax-bouazzouni** [comment]
The generic issue here is that when we create an issue we need to add DNS redirection and also add an HTTP certificates:

- [RDA Rice Data Interoperability working group (rice)](http://rice.https//agroportal.lirmm.fr)
- [Crop Ontology Curation Tool (crop)](http://crop.https//agroportal.lirmm.fr)
- [OBO Foundry (obo-foundry)](http://obo-foundry.https//agroportal.lirmm.fr)
- [The Agronomic Linked Data (AgroLD) (agrold)](http://agrold.https//agroportal.lirmm.fr)
- [Consortium of Agricultural Biological Databases (agbiodata)](http://agbiodata.https//agroportal.lirmm.fr)
- [SemanDiv working group (semandiv)](http://semandiv.https//agroportal.lirmm.fr)
- [RDA Wheat Data Interoperability working group (wheat)](http://wheat.https//agroportal.lirmm.fr)
- [Exclusive AgroPortal ontologies (exclu)](http://exclu.https//agroportal.lirmm.fr)
- [National research institute for agriculture, food and the environment (inrae)](http://inrae.https//agroportal.lirmm.fr)

**Comment by syphax-bouazzouni** [comment]
A support mail was sent to index LIRMM. See again in two weeks

**Comment by syphax-bouazzouni** [comment]
Step to do as user centos:
* Add for each slice a line  `  ServerAlias *.agroportal.lirmm.fr` to the file `/etc/httpd/conf.d/10-appliance.ontoportal.org_non-tls-le-ssl.conf`  and to be like bellow:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
  ServerName agroportal.lirmm.fr
  ServerAlias crop.agroportal.lirmm.fr
  ServerAlias planteome.agroportal.lirmm.fr
  ServerAlias obo-foundry.agroportal.lirmm.fr
  ServerAlias agbiodata.agroportal.lirmm.fr
  ServerAlias semandiv.agroportal.lirmm.fr
  ServerAlias agrotermos.agroportal.lirmm.fr
  ServerAlias wheat.agroportal.lirmm.fr
  ServerAlias exclu.agroportal.lirmm.fr
  ServerAlias inrae.agroportal.lirmm.fr
  ServerAlias dtokab.agroportal.lirmm.fr
```

* Create an https certificate for all the slices by running this command: 
```bash
systemctl reload httpd
certbot -d agroportal.lirmm.fr,planteome.agroportal.lirmm.fr,crop.agroportal.lirmm.fr,obo-foundry.agroportal.lirmm.fr,agbiodata.agroportal.lirmm.fr,semandiv.agroportal.lirmm.fr,agrotermos.agroportal.lirmm.fr,wheat.agroportal.lirmm.fr,exclu.agroportal.lirmm.fr,inrae.agroportal.lirmm.fr,dtokab.agroportal.lirmm.fr --apache
```

<img width="930" alt="image" src="https://github.com/user-attachments/assets/72e0f583-38c4-4496-8cce-cb0f75e7b2ed">
