### ISSUE TITLE
Afficher les vues donc un utilisateur est admin dans la page "Account" 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#270]
Nous avons une section "Submitted ontologies" dans la page Account. Il semblerait que cette setion n'affiche pas les ontologies pour lesquelles un utilisateur est admin. Je pensais que c'était le cas.

Voir e.g. maweber qui ne voit pas les ontologies dont elle est admin dans sa page account.

Je propose: 
- [x] Changer le mécanisme de recuperation des ontologies dans cette vue pour afficher toutes les ontologies dont un utilisateur est  admin (ce qui incluera toutes celles qui'il/elle a soumise).

**Comment by jonquet** [comment]
Apres vérification avec @SirineMhedhbi nosu avons vu que c'est bien les ontologies "administratedBy" qui sont récupérées. 

Par contre ces ontologies ne contiennent pas les vues. Il s'agit donc de expplicitement recupérer les vues aussi.

**Comment by jonquet** [comment]
@SirineMhedhbi Finalement je pense c'est pas nécessaire de changer le titre de la section. 
Par contre, je propsoe de revenir sur une choix graphique est de lister les ontologies tjrs dans un "bouton" mais à l'aide des acronymes, pas des noms. Pour que cela soit plus succint comme visu.

**Comment by syphax-bouazzouni** [comment]
### To validate/reproduce 

1. Have a user 
2. Go to an ontology (O1) and add your user as an admin to that ontology
3. Go to a view (V1) (**that is not related to the ontology in 2 (O1)** ) and add your user as an admin to that view
4. Go to the user account page, and you should see the submitted ontologies section, the ontology in 2. (O1), and the view in 3. (V1)

**Comment by SirineMhedhbi** [comment]
@syphax-bouazzouni  fixed 
see this commit : https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/286/commits/31e07358ac17300678dbe36f58f32c1d1c275483

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/291 and https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/286
