### ISSUE TITLE
clicking on the reset password link sent by email does not work

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#276]
### Use case 
See agroportal-support mail  from Magalie Weber <magalie.weber@inrae.fr>
To reproduce 

1. Go to forgot password page  : https://agroportal.lirmm.fr/lost_pass
2. Write an existing email
3. Go to the received email and click on the link.

![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/a561181a-5b6e-4992-834b-7a17041f1373)

**Comment by SirineMhedhbi** [comment]
It works
I tested it in Agroportal , Stageportal and Testportal

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/31127782/7998c212-f171-4b0f-947b-6bc2279ab27d)

**Comment by syphax-bouazzouni** [comment]
The correspondant logs: 
```
F, [2023-06-30T16:32:30.921817 #11633] FATAL -- :   
NoMethodError (undefined method `match' for nil:NilClass):
  
app/controllers/users_controller.rb:253:in `validate_update'
app/controllers/users_controller.rb:80:in `update'
```

**Comment by syphax-bouazzouni** [comment]
Fix with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/287
