### ISSUE TITLE
Bug : after search : the redirect for an empty search page and hidden popup

### ISSUE THREAD

**Issue by SirineMhedhbi** [ontoportal-lirmm/bioportal_web_ui#308]
### Issue 
- The first bug : 
 After performing a search and clicking on the 'details' button, a popup opens. However, when clicking on the arrow in the section  'related' , the redirection leads to the wrong page (search page)

- The second bug : 
 After performing a search and clicking on the 'details' button, a popup opens. However, when clicking on the arrow in the 'altLabel' section, another popup is hidden and opens instead.

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/31127782/ea6d21f3-59a4-419b-b4c7-a212a8925e04)

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/31127782/5c5f422c-1abd-48e6-8916-af481f7c987c)

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/31127782/71ee3861-8602-4a33-bd08-7d36e9bf9842)

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/31127782/536ae92c-b2b2-44ff-9e29-5eda9430ddb6)

### Requirements
- [x] Redirect to the right page.
- [x] Fix the problem of hidden popup.

**Comment by syphax-bouazzouni** [comment]
fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/317
