### ISSUE TITLE
Small changes on the account creation page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#315]
Tested on new EcoPortal. 

- Change error message for ORCID validation to "Please enter a valid ORCID."
- Change the "Password / Confirm password" fields to be detectable by Browser so that a "password suggestion" is proposed by browser. 
- Change the "hardcoded" message "Register to the AgroPortal's mailing list" by => Register to the *portal name* 's ** announcements** mailing list."
- Errors in creating the account re-open the account creation form but remove the First name and Last Name values
- Display errors consistently => In the follwing image remove [:error , "...."] a leave only the error message (as with the other errors)
<img width="434" alt="Capture d’écran 2023-08-01 à 09 24 06" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/0393503d-8c23-4783-b700-2f1ef2d97823">

(side note: on EcoPortal test, I never got the email with instructions)

**Comment by jonquet** [comment]
- Clicking back after "error in creating an acocunt" brings us to /accounts and the following message
 
<img width="1008" alt="Capture d’écran 2023-08-01 à 09 26 21" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/e86e7240-1c52-4b27-9be8-e35949ad5e50">

Instead of bringing you back to the /login page

**Comment by syphax-bouazzouni** [comment]
@SirineMhedhbi is this fixed? If yes please close this.

**Comment by SirineMhedhbi** [comment]
@syphax-bouazzouni I haven't started the task yet

**Comment by syphax-bouazzouni** [comment]
yes, sorry I mistook it with  this one https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/353

**Comment by syphax-bouazzouni** [comment]
fix with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/401
