### ISSUE TITLE
Small changes on "My account" page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#316]
- Personal information => capitalize the I of information as the other section title in the page are capitalized at each words. Idem for "Mailing list subscription"
- Change "Email adress" by "Email => to be consitent with form.
- Change "AgroPortal announcements email list" => with generic portal name
- Change the sentence  "Your API Key can be used to access the NCBO API (REST) Services" by "Your API Key can be used to access **portal name** Web services
- Change API link to portal specific one
- Change  to "Customize your **portal name** display: Pick the semantic resources that you want to see on "portal name " and we will hide all other resources."
- "Select semantic resources" => Capital S at Select
- Note : this => without capital t
- You didn't upload any semantic resource yet (without S to resources)
- Change occurence of word "ontologies" to semantic resources" everywhere => 
<img width="279" alt="Capture d’écran 2023-08-01 à 15 00 39" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/0a200f8b-0b66-41dd-8655-9a656a5cbe41">
<img width="456" alt="Capture d’écran 2023-08-01 à 15 01 09" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/2e02dc36-8ea5-4e79-a72f-fcf2e99f0bb2">

**Comment by syphax-bouazzouni** [comment]
@SirineMhedhbi is this fixed? If yes please close this.

**Comment by SirineMhedhbi** [comment]
@syphax-bouazzouni  yes fixed
