### ISSUE TITLE
Feedback window doesn't work

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#325]
### Problems
- When we click on submit feedback button, the window doesn't popup,
- The feedback doesn't work,
- We can't select multiple tags (bug in chips)

### Screenshot
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/63ccfcdd-ece3-49de-bf98-b3598ac89945)

**Comment by syphax-bouazzouni** [comment]
fixed by #349 


![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/06b6f6e3-3be5-4778-a45f-24cc99aacfce)
