### ISSUE TITLE
Security Issue: Unlimited Wrong Email and Password Logins

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#327]
### Description
I have identified a security concern on our website related to the authentication system. Currently, there is no limit on the number of wrong email and password login attempts a user can make. This could potentially expose our platform to various security risks.

### Impact
- **Brute Force Attacks**: Attackers could use automated tools to guess passwords and gain unauthorized access.
- **Resource Exhaustion**: Unlimited incorrect login attempts could lead to server resource exhaustion and potential denial-of-service attacks.

### Recommended Action
- Implement a reasonable limit on the number of failed login attempts per user within a specified time frame.

**Comment by syphax-bouazzouni** [comment]
I think we have something in the API to prevent that, called [Rack::Attack](https://github.com/ontoportal-lirmm/ontologies_api/blob/master/config/rack_attack.rb), do yo confirm @alexskr?

**Comment by alexskr** [comment]
Rack Attack is currently configured to throttle requests which can help with the resource exhaustion but it would not be enough to mitigate brute force login attacks at the moment.   It would be a good idea to configure rack attack to limit login attempts as well.

It is important to note that Rack Attack is [not currently enabled by default](https://github.com/ncbo/virtual_appliance/blob/0ec161eed243b64f2a42b960d609f94e01212492/appliance_config/ontologies_api/config/environments/appliance.rb.default#L119C5-L119C47) in the appliances.

**Comment by syphax-bouazzouni** [comment]
> Rack Attack is currently configured to throttle requests which can help with the resource exhaustion but it would not be enough to mitigate brute force login attacks. It would be a good idea to configure rack attack to limit login attempts as well.
> 
> It is important to note that Rack Attack is [not currently enabled by default](https://github.com/ncbo/virtual_appliance/blob/0ec161eed243b64f2a42b960d609f94e01212492/appliance_config/ontologies_api/config/environments/appliance.rb.default#L119C5-L119C47) in the appliances.

Yes, I confirm, that it is disabled in Agroportal, any reason to enable it by default?

**Comment by alexskr** [comment]
I think throttling should be enabled by default. 

If throttling is enabled then API access would be limited to:
- 3 requests per second for [heavy requests](https://github.com/ncbo/ontologies_api/blob/0402dc47970e18271930cf648f023e590615f9d2/config/rack_attack.rb#L32-L34) (annotator and recommender) 
- 15 requests per second for all others

Default 15 req/sec is most likely not restrictive enough for small installation but would provide at least some sort of a ceiling.

**Comment by syphax-bouazzouni** [comment]
Issue moved to https://github.com/ncbo/virtual_appliance/issues/38 and https://github.com/ncbo/ontologies_api/issues/128
