### ISSUE TITLE
Edit group and categories button in new admin UI generate a bug

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#332]
On stageportal.

Go to Category admin page and click on Edit a category.
<img width="237" alt="Capture d’écran 2023-08-28 à 16 18 19" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/95f7d509-5b6e-4f8b-91be-c2fc3e93aff8">

Click on Edit category and a bug appear. 
<img width="215" alt="Capture d’écran 2023-08-28 à 16 19 08" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/b190ad7a-1c4f-44aa-8699-2d427a92da21">

Same with Groups.

**Comment by syphax-bouazzouni** [comment]
fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/334 (don't forget to close the issue when work is done @SirineMhedhbi)
