### ISSUE TITLE
remove handlebars dependecy and update ontology properties tab to use plain HTML

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#341]
### Context
Currently, we have a deprecated (in 2019) dependency called [Handlebars](https://handlebarsjs.com/), it is a templating language tool, Used only in one place, the ontology properties tab (https://stageportal.lirmm.fr/ontologies/AGROVOC/?p=properties).

### Requirements
- [x] Remove Handlebars dependency (https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/development/app/views/layouts/_header.html.erb#L27)
- [x] Migrate the properties tabs to Ruby and HTML, as the others tabs (related code https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/development/app/views/ontologies/sections/properties.html.haml)

**Comment by syphax-bouazzouni** [comment]
Issue after the new version of https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/346 , in Testportal
<img width="1253" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/742be848-2df4-46a3-b91e-7645112b0f16">

**Comment by SirineMhedhbi** [comment]
@syphax-bouazzouni  fixed
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/31127782/1131e540-ccf3-43a6-9cdb-45fed8db6ebf)

**Comment by syphax-bouazzouni** [comment]
Another issue is that if there is an ontology that does not have properties,  the loader shows forever 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/16b7b8b7-8559-4f90-8bd5-36040773aff7)

**Comment by SirineMhedhbi** [comment]
@syphax-bouazzouni i will take care of this

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/405
