### ISSUE TITLE
Probleme a l'affichages des details dans la soumisison d'une nouvelle submisison

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#342]
Sur AgroPortal, au chargement d'une soumission, les "advanced options" ne s'affichent plus 

<img width="726" alt="Capture d’écran 2023-09-11 à 12 56 19" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/ae0050ec-bf13-4404-927c-75954dc8c702">

**Comment by syphax-bouazzouni** [comment]
This bug is known and is fixed in Stageportal in the new UI.
<img width="1380" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/a7a13e96-65e4-4a63-8980-2640797db85d">

@jonquet do you want it to be fixed in Agroportal,  meantime Stageportal is ready?
