### ISSUE TITLE
See what the todo in the bioportal web ui README.md

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#382]
This repository READMD, need to be cleanded

**Comment by syphax-bouazzouni** [comment]
Any news  @jonquet ?

**Comment by jonquet** [comment]
Thought I did it already... hum ill do again ;.

**Comment by jonquet** [comment]
I do not see anymore work to do for the moment on
https://github.com/ontoportal-lirmm/bioportal_web_ui/blob/master/README.md

I would suggest our ReadmeS on ontoportal-lirmm to stay minimalist and maybe just mentionned that we are an extension of our forks (mostly backward compatible) with new features as detailed in the Releases notes (AgroPortal).

Later, the Alliance will have to update rigourlsy all the readmeS of all the repos on https://github.com/ontoportal
