### ISSUE TITLE
Ontology network in landscape page display AgroPortal ontologies in blue

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#4]
Le graphique 'ontology network' de la page Landscape affiche les ontologies d'AgroPortal en bleu (avec l'URL longue) au lieu de les afficher en vert (simplement avec l'acronyme). En plus, l'information dans le graphe est dupliquée.

**Comment by syphax-bouazzouni** [comment]
Fixed 


![Image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/02b4ea41-6ac4-4438-b73b-0694bcbb55a9)

Please close @jonquet , if done.

**Comment by jonquet** [comment]
This is technically fixed (https related) and curated (from @hibadjebabria169 work) to the max we can do before the production release. We will curate again with new UI and metadata model.
