### ISSUE TITLE
Add a section to point to the other portals same as Supported by and with the collaboration of.

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#434]
### Context
Agroportal is an instance of the Ontoportal technology, distributed and maintained by the Ontoportal alliance members, for today we count the following Ontoportal instances, in addition to Agroportal: Bioportal, Bioportal SIFR, EarthPortal, Ecoportal,  BioDivportal, Indsutryportal, MedPortal, and Matportal. (see the ontoportal website https://ontoportal.org for an updated list) 

###  Goal 

A good thing to have is that on each portal, on the homepage a section, lists all the Ontoportal instances, with logos and links to them.

This will help people find them more easily, and be the first brick of a federation system in the future.

### Requirements 

- [ ] Be configurable, and defined in the configs files of the portal 
- [ ] Be a section in the homepage, that have the logos and links to the portals 
- [ ] When clicked open a new tab to the portal

**Comment by syphax-bouazzouni** [comment]
Done in #524
