### ISSUE TITLE
Upload ontology form error state, erroned submited values not returned

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#437]
The source is https://docs.google.com/spreadsheets/d/1lEdrxJKKOJYbSYH_Ptzu2dUliHAKcFTirrw8vs9Hcuk/edit#gid=713725591&fvid=1197518333 document.
Details need to be provided here

**Comment by Bilelkihal** [comment]
https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/625

**Comment by syphax-bouazzouni** [comment]
Re-opened it, as the PR (https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/625) is only in draft state, will close this when the PR is approved.

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/625
