### ISSUE TITLE
Issue with the watch button title not showing always the right information

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#441]
watch and unwatch, not show the double title if hower and downcase, and add space.
source: https://docs.google.com/spreadsheets/d/1lEdrxJKKOJYbSYH_Ptzu2dUliHAKcFTirrw8vs9Hcuk/edit#gid=713725591&fvid=1197518333

**Comment by syphax-bouazzouni** [comment]
> I couldn't understand what do u mean exactly, can you clarify more @syphax-bouazzouni

@Bilelkihal Here are the details:
1. https://github.com/agroportal/project-management/issues/567
2. When not connected clicking on watch returns content missing 
<img width="437" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/fd67e148-72d6-42d8-91c2-638326b28a0a">
3. When you are not watching an ontology and click on the watch button , the tooltip text is not updated to say "Unwatch" 
<img width="516" alt="image" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/9671192a-31f7-4ae3-a150-01431e3266ec">
4. Replace "UnWatch" to "Unwatch"

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/681
