### ISSUE TITLE
Add in the "Date and contacts" add the "Repository" property under contacts

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#461]
Source: https://docs.google.com/spreadsheets/d/1lEdrxJKKOJYbSYH_Ptzu2dUliHAKcFTirrw8vs9Hcuk/edit#gid=713725591&fvid=1197518333

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/95b72ae3-2d6a-49d7-8f6c-2c8a221445e1)

**Comment by jonquet** [comment]
Not sure I understand what to do here.

**Comment by syphax-bouazzouni** [comment]
> Not sure I understand what to do here.

@jonquet requirement came from you, you can give more details if needed. Or close it if no more required.

**Comment by jonquet** [comment]
Laissons tombé. Pour le moment le process de soumission demande assez de meta-données.
