### ISSUE TITLE
Metadata administration "inculde all submissions" does not work anymore

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#486]
See example on picture.

<img width="1160" alt="Capture d’écran 2024-02-01 à 23 15 39" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/24a7d9fe-851a-468e-8a87-45eb7a51f3ca">

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/551
