### ISSUE TITLE
Deleting a submission from the UI results in error message

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#521]
Experienced today with deletion of submission 23 from NCBITAXON thru the Summary page. 

Here is the result: 

<img width="613" alt="Capture d’écran 2024-03-07 à 17 05 30" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/a5f6fe0d-a7ed-479c-9037-fb98fef29ca7">

Flushing the UI cache and refreshing shows the deletion has not been processed in the back. 
So say the folder on server whcih still contains the submission folder.

**Comment by syphax-bouazzouni** [comment]
same as https://github.com/agroportal/project-management/issues/481

**Comment by jonquet** [comment]
Then closing. 
Note that Ihave manually remove NCBITAXON 23 from ncbo_cron
