### ISSUE TITLE
Summary shortcut buttons should open to another Windows

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#522]
Tested on NALT: 
https://agroportal.lirmm.fr/ontologies/NALT

<img width="499" alt="Capture d’écran 2024-03-07 à 17 51 11" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/25ed86a9-e4e8-4a27-9ac5-e3691c6b6ced">

**Comment by syphax-bouazzouni** [comment]
is it the same in stageportal ? @jonquet

**Comment by syphax-bouazzouni** [comment]
Fixed in #531
