### ISSUE TITLE
Overflow of text on the navbar search input results

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#525]
screenshot:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/8ce5056c-ee1d-4c9f-9115-9a1392f1f9dd)

**Comment by syphax-bouazzouni** [comment]
I did a first iteration on this here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/505/commits/e71fd4e39adb7c208687e1dda37c6fb56ce87c08

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/505
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/ef9feee0-4710-4df7-b220-3d6b2cf0fd06)
