### ISSUE TITLE
URL/URI value in our Raw data UI are clickable but not necessarily open somewhere

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#528]
Got to 
https://agroportal.lirmm.fr/ontologies/SFWO/?p=classes&conceptid=http%3A%2F%2Fpurl.org%2Fsfwo%2FSFWO_0000061&jump_to_nav=true

See the property 
<img width="502" alt="Capture d’écran 2024-03-08 à 11 36 04" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/dd0eb134-ec68-415e-b36e-90fe1274b1dc">

Click on the ORCID URL end up on a 404 has we try to open it in AgroPortal

**Comment by SirineMhedhbi** [comment]
@jonquet it works, test again

**Comment by jonquet** [comment]
En effet au refresh de la page j'ai bien le lien qui s'ouvre dans une autre fenêtre chez ORCID. 
Est-ce que tu as changé qq chose ?  ou est-ce que je dois comprendre qu'il y avait une histoire de cache ou autre en local ?

**Comment by SirineMhedhbi** [comment]
@jonquet  j'ai rien changé , j'ai juste testé pour voir le bug

**Comment by syphax-bouazzouni** [comment]
To reproduce 
* Click https://agroportal.lirmm.fr/ontologies/SFWO/?p=classes&conceptid=http%3A%2F%2Fpurl.org%2Fsfwo%2FSFWO_0000061&jump_to_nav=true
* In the tree view, click on another concept 
* go back to the previous concept, by clicking again on the previous concept in the tree 
* now when clicking on an external link example OCRID, it redirect to Agroportal 404 page

**Comment by Bilelkihal** [comment]
fixed in: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/638
