### ISSUE TITLE
UI instances issues : compressed table and details opens on the side

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#53]
http://agroportal.lirmm.fr/ontologies/BIOREFINERY/?p=instances

For this ontology (only, but others are affected e.g., TOP) the instance tables display compressed on the left and details opens half on the side. see picture.
<img width="663" alt="Capture d’écran 2022-01-20 à 14 25 20" src="https://user-images.githubusercontent.com/7379183/150347806-e6b5ed4e-04d4-42e5-9765-1845e6c9a2ac.png">

**Comment by syphax-bouazzouni** [comment]
Fixed and deployed in production (agrportal+bioportal), tag 2.1.1
