### ISSUE TITLE
Erreur au lancement d'une actin sur une ontologie via la page admin

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#533]
Essai sur CO_356. 
Page Admin>Ontology adminstration
Select CO_356
Process
Go

=> Genere une erreur

<img width="374" alt="Capture d’écran 2024-03-12 à 10 49 37" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/f55821c3-6f72-479e-92df-18663116e423">

**Comment by syphax-bouazzouni** [comment]
Same as #532

**Comment by syphax-bouazzouni** [comment]
Fixed in #541
