### ISSUE TITLE
Display sub-tabs for Instances

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#536]
In the user interface, we have sub-tabs for Classes/Concepts. As illustrated:

<img width="968" alt="Capture d’écran 2024-03-13 à 13 52 10" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/5d7ce279-c296-4702-b4b8-dfbdefbdde64">

This issue is about the relevance of having sub-tabs for Instances too:

<img width="953" alt="Capture d’écran 2024-03-13 à 13 52 41" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/98f727b4-2083-48a1-b845-aeed3457fbbd">

Possible tab would be:
- Details. Show the instance info as we display the class info.
- Visualization (un the future we could think of a visu)
- Notes (assuming we can create in the back-end a note on an instance)
- Mappings (we could have mappings between instances
- {} button to go directly to the instance detail API call

**Comment by jonquet** [comment]
Related to #535

**Comment by syphax-bouazzouni** [comment]
Notes and mappings are done only in Concept/Classes, so this feature request to be achieved need a lot of changes of the backend, in the notes and mappings features.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/754 for the implementable tabs
