### ISSUE TITLE
Add terms and conditions links to the footer

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#543]
We need to add to the footer some links that direct users to specific sections within our terms and conditions page, such as 'Legal Notices' ...

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/9f241b99-6d25-489c-b02e-2e65dfd38e38)

**Comment by syphax-bouazzouni** [comment]
Done in #579
