### ISSUE TITLE
Create a new dynamic route for ontologies content derefrencement 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#545]
### Context
See  https://github.com/agroportal/project-management/issues/476

### Goal 

Have a human-readable URL/URI for users to access ontologies content in Agroportal, e.g https://agroportal.lirmm.fr/ontologies/INRAETHES/d_1 that will redirect to https://agroportal.lirmm.fr/ontologies/INRAETHES?p=classes&conceptid=http://opendata.inrae.fr/thesaurusINRAE/d_1

### Requirements 

- [ ] Add a dynamic route in the routes.rb file to match `get "ontologies/:acronym/:id"` and redirect to a new ontologies controller action called for example `show_redirection`
- [ ] In this new controller action if the `:acronym` does not exist return not found 
- [ ] If the `:id` is not a URL, create a function that will find the full URL, using one of these methods: 
        -  use the indexed data, to URI that matches the given `:id`.  
        -  use the ontology metadata (URI, Identifier pattern, Preferred namespace URI) to deduce the full ID.
- [ ] Once the full ID is found, get the id `type` from  the index or triple store, and by  the type redirect to the correct page, follow the bellow cases: 
```ruby
  def ontology_link_by_type(id, acronym, type)
    case type
    when 'Concept', 'Class'
      ontology_path(id: acronym, p: 'classes', conceptid: id)
    when 'Ontology'
      ontology_path(id: acronym, p: 'summary')
    when 'ConceptScheme'
      ontology_path(id: acronym, p: 'schemes', schemeid: id)
    when 'Collection'
      ontology_path(id: acronym, p: 'collections', collectionid: id)
    when 'NamedIndividual'
      ontology_path(id: acronym, p: 'instances', instanceid: id)
    when 'AnnotationProperty', 'ObjectProperty', 'DatatypeProperty'
      ontology_path(id: acronym, p: 'properties', propertyid: id)
    else
      # link to content find a tool, something like this  "/content_finder?acronym=#{acronym}&uri=#{id)}&output_format=xml"
    end
  end 
```

Below is a diagram summarizing the process 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/71cecab5-1018-4340-b059-35f58b6715b7)

**Comment by syphax-bouazzouni** [comment]
@imadbourouche , Important to note that the redirection needs to be content negotiable also, so if we as XML don't show the Agroportal UI and directly redirect the XML content returned by the back.

**Comment by imadbourouche** [comment]
> @imadbourouche , Important to note that the redirection needs to be content negotiable also, so if we as XML don't show the Agroportal UI and directly redirect the XML content returned by the back.

if we specify the accept format (json, ntriples, turtle, xml), the result will be the content of the resource in the format specified (it means that it will be no redirection to html page)
if the accept header is "text/html" we will redirect the user to Agrportal UI page for the resource

Am I correct in this ?
