### ISSUE TITLE
Changing to "All languages" when browsing doest not always keep the current page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#557]
Go to: 
https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&language=pt&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_d41ccef2

And click the language selector to "All languages"=> the page shows all the language for the SAME concept without 

Now go to 
https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&language=pt&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_d41ccef2
then in the hierachy click on 
grupo
then on 
agente florestal
then on c_d41ccef2 

And click the language selector to "All languages"=> the page change and go back to "activities" one of the top level concept.

**Comment by Bilelkihal** [comment]
I could not reproduce this issue:

https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/1c4031d5-3b0b-4cef-b3fe-daee64f5994a

**Comment by jonquet** [comment]
OK it's. abit more tricky that expected... 

Start from an empty page. 
Go to https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&language=pt&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_d41ccef2

Then change to "All languages"
Ok we stay on the right page (and URL change to https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&language=all&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_d41ccef2)

Now click to "priest of the land" under land practioners (sibling of foresters).
URL change to https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&language=all&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_28f78be5

Now click "Portuguese" 
=> the UI brings you back to c_d41ccef2 (the latest concept browsed for which there was no label in the selected language)
and the URL change to 
https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&language=pt&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_d41ccef2
rather than https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&language=pt&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_28f78be5

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal see also https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/617
