### ISSUE TITLE
Petite amélioration de la Search box home page et bandeau

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#570]
Comme illustré sur le screenshot on voit "Ontology" sur la droite pour les 2 cas. 

<img width="535" alt="Capture d’écran 2024-04-09 à 17 26 59" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/45c61130-75e7-439d-90d0-da998a43105f">

Tandis que pour le premier (FCUO) on pourrait voir "Ontology view" car FCUO est une view. 

Peut etre cela sera traité avec les nouveaux index.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/596

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/b86f3d1e-4677-4406-904c-b6ab6112bbf8)
