### ISSUE TITLE
Connect the footer to the Terms and Conditions

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#573]
We have now our first version of the Terms & Conditions online here: 
https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412

This issue is about changing the AgroPortal footer to point to them:

In English I propose the following titles and links:
**Legal**
- Terms and Conditions => https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-and-conditions-naDsDo2Zxq#h-terms-and-conditions-english
- Privacy Policy => https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-and-conditions-naDsDo2Zxq#h-terms-and-conditions-english
- Legal Notice => https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-and-conditions-naDsDo2Zxq#h-legal-notice

In French I propose the following titles and links:
**Informations légales**
Conditions générales d’utilisation => https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-and-conditions-naDsDo2Zxq#h-conditions-generales-dutilisation-francais
- Vie privée => https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-and-conditions-naDsDo2Zxq#h-vie-privee
- Mentions légales => https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-and-conditions-naDsDo2Zxq#h-mentions-legales

**Comment by syphax-bouazzouni** [comment]
Done #579
