### ISSUE TITLE
Annotator returns result with multiple languages (instead of english only)

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#577]
The annotator returns result with different languages, while it's supposed to return them in english only

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/085e1f72-3134-43a4-bf1e-a1140a886a89)

**Comment by Bilelkihal** [comment]
This is not related to the new annotator's ui code,
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/3df4663a-20d3-4370-80e8-bb9d5646542e)


The annotator's service returns results in multiple languages.
![Group 2305](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/d4aeb3c4-8900-4758-9de5-ca742c162372)


As a proposition to not go into the annotators code, we can in the UI fetch every concept by its id then display the default pref label of it which is in english, 
@jonquet  What do you think ?

**Comment by jonquet** [comment]
Hello. This is probably a change/bug introduced when we implemented the multilingual support. 
We can see that the match (against the Annotator Redis dictionnary) was made with "Air temperature" in AGROVOC. The issue come from the call to retrieve the Class object from the key we have back from the MGREP tool. We might have not put the default language or something like this in this call.. so when there are multiple labels (as in AGROVOC but not in AGRO) we get one prefLabel randomly.

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal did you try to add to the annotator api call, the language parameter (e.g `lang=en`)

**Comment by jonquet** [comment]
Pour moi c'est un changement sur l'Annoator back end a faire puisque le service web renvoie pas non plus ce qu'il faut.

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/ontologies_api/pull/82 and deployed on StagePortal, will be deployed with [Release 2.9.1](https://github.com/agroportal/project-management/issues/537)
