### ISSUE TITLE
Search page, some concepts links are not working

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#578]
### Example
https://agroportal.lirmm.fr/search?q=yield+&lang=all&ontologies=CSOPRA

clicking on the result throws an error:
https://agroportal.lirmm.fr/ontologies/CSOPRA?p=classes&conceptid=http://csopralibs.org#Yield

### Reason:
IDs of concepts need to be encoded, in this case:
https://agroportal.lirmm.fr/ontologies/CSOPRA?p=classes&conceptid=http://csopralibs.org%23Yield
works.

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/583
