### ISSUE TITLE
Saisir une valeur autre que celles proposée par "Natural language" crée un erreur 404

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#586]
Essayer avec E-PHY essayer d'ajouter "fr-CA" comme language. 
Ou AGROVOC avec pt-BR

Cela génère une erreur 404 tandis que cela devrait renvoyer un message d'erreur disant que le champ accepte que des URIs. In fact, I suggest we constraint even more this field so that ONLY URIs from Lexvo are accepted and a message would say: "Contact support to add support for another language"

**Comment by syphax-bouazzouni** [comment]
done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/663
