### ISSUE TITLE
Agent edition form still shows "Affiliation" when "Organization" is selected.

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#589]
<img width="736" alt="Capture d’écran 2024-04-22 à 23 15 36" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/7dbb56bb-5771-47cd-8f97-cfaa1a7ffcf1">

I remember we decided to remove it.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/696
