### ISSUE TITLE
Agent filtering inthe admin "Person and organization" does noit use the ACRONYM property

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#591]
<img width="1024" alt="Capture d’écran 2024-04-22 à 23 27 10" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/121ae7a6-8dbf-4400-aaaa-ed4dca77ef97">

This makes the filtering/search very cumbersome.

**Comment by Bilelkihal** [comment]
Fixed in: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/704#event-13398539604
