### ISSUE TITLE
Des erreurs d'edition qui empêchent le nettoyage des agents

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#592]
A essayer sur "W3C"

<img width="1140" alt="Capture d’écran 2024-04-22 à 23 38 40" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/ca8d7d03-4798-43e5-adb0-9fe72f583b0c">

Il faut supprimer la 1ere, 2eme et 3eme ligne. 

Le bon agent W3C est trouvable avec "world wide" . Il est censé deja avoir les valeurs des usages des agents qu'il faut supprimer.

**Comment by jonquet** [comment]
En fait le bug qui revient le plus est celui d'un agent dont on edite les usages pour les supprimer et cela ne marche pas... on peut donc jamais le supprimer. 
J'ai essayer en rechargheant la page ... parfois ca marche. 
En vidant les caches... sans effet.

**Comment by syphax-bouazzouni** [comment]
Qu'on essaye d'enlever un usage a un des ces Agents, on tombe cette page d'erreur; a invistiguer.
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/e1c34d1f-f777-46b5-920a-3e5193db53f4)

**Comment by galviset** [comment]
J'ajouterais un autre problème d'édition que j'ai aussi constaté sur EarthPortal: en essayant d'ajouter un ORCID, je tombe sur cette erreur:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/44084050/7e64185b-685f-4607-a138-d548704fd15a)

**Comment by Bilelkihal** [comment]
Il y a deux problèmes distincts là:

- Le premier est une erreur causée par un bug dans le code, qui a été corrigée ici : https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/697

- Le deuxième problème concerne certaines ontologies ayant des agents non valides, ce qui empêche de sauvegarder les soumissions lorsqu'on les édite.
comme par exemple AGROVOC:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/6797ae84-9872-47f9-b77f-b9cb7c3e8ed8)
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/3eaea17d-cfbd-4410-8ee0-3b0c16df9ed1)

**Comment by Bilelkihal** [comment]
Donc faut faire un travail de curation pour les ontologies utilisant l'api directement (c'est pas possible dans l'interface admin) psq ça concern des agents qui sont pas valides
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/9511f590-1a6b-4de0-bb17-f44b32b4c648)

**Comment by jonquet** [comment]
Discuté ce jour. 
Passer par le cron pour vérifier la validité des agents. Si non valide (et aucune info dessus) alors on supprime pour ne plus rencontrer l'erreur de modification d'une ontologie mentionné dans cette issue.

**Comment by syphax-bouazzouni** [comment]
Cleaned, there were only one not valid agent
