### ISSUE TITLE
Une recherche dans une langue doit permettre de continuer a naviguer le contenu dans cette langue

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#594]
Go to /search
Search for "pastagem" in portuguese 
https://agroportal.lirmm.fr/search?q=pastagem&lang=pt

See the result in AGROVOC and click.
You go there : 
https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&conceptid=http://aims.fao.org/aos/agrovoc/c_5626

Ideally you would go there: 
https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_5626&language=pt

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/595
