### ISSUE TITLE
Disparition du message informant qu'il y a pas de propriété (cas de STY)

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#600]
Dans les dernieres releases, on a perdu le message sur STY qui dit qu'on a pas de propriété: 
SIFR BioPortal
<img width="287" alt="Capture d’écran 2024-04-27 à 08 31 43" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/53e5b1ba-b139-4d4e-8e8f-5d27737d57cd">

AgroPortal
<img width="381" alt="Capture d’écran 2024-04-27 à 08 32 06" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/cc25a646-0e3d-48e1-9ea4-b987ed1ab99f">

It could be put back with the similar notificaiton system we use now: 
<img width="1066" alt="Capture d’écran 2024-04-27 à 08 33 45" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/45eee815-ec21-4328-81c4-43330ce7c179">

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/613

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/1337dea0-249e-42ec-8c56-174079ec0837)
