### ISSUE TITLE
Ajouter un lien dans le chemin des ontologies quand on est sur une vue

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#602]
Quand on est sur une vue et qu'on voit le chemin 

<img width="294" alt="Capture d’écran 2024-04-27 à 09 33 04" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/79b84dd1-4049-4878-a7c3-f724deb4b360">

L'ontologie principale (ici PPDO) pourrait etre un lien nous rameenant explicitement vers l'ontologie principale. 

A noter aussi sur le meme chemin je mettrai "ontologies" avec une majuscule "Ontologies"

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/643
