### ISSUE TITLE
Erreur de pharse en haut des métadonnées sur la page edit submsision

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#603]
<img width="742" alt="Capture d’écran 2024-04-27 à 09 50 21" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/8a4c1955-d28e-4cd7-a652-324e4029f698">

Manque le lien.

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/613
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/93fe755e-0938-45b2-9896-052e43a5e4e4)
