### ISSUE TITLE
Can't find some ontologies in the browse page and the ontologies selector

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#607]
## Problem
Some ontologies are only discoverable through the homepage and navigation bar search, missing from the browse page and ontology selector results.

## Example:
looking for the ontology FCUO (French Crop Usage Ontology) on AgroPortal:
- ### In the browse page:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/fb125df1-1403-432a-93ea-98fe88005f45)
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/cb13925b-0c61-4db0-b4a1-c4858c075ec6)

- ### In the home_page/nav_bar search:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/eeeaf0bd-0d0b-4675-8389-9f8554d1c3d5)

- ### In the different ontologies selectors:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/912e29cb-9d03-45b2-831d-1f448b8acb81)
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/31ef1453-e4bb-4db1-a226-06a58b1aebf3)

- ### The summary page of the ontology
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/06fd14b9-ccd9-40ba-950c-1961861ae174)

**Comment by syphax-bouazzouni** [comment]
@Bilelkihal it is because it is a View, in browse page you need to enable the views switch, same for the selector.

**Comment by Bilelkihal** [comment]
Yes, I didn't notice, thanks
