### ISSUE TITLE
Manque un synonyme dans l'affichage d'un concept

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#609]
Aller a
https://stageportal.lirmm.fr/ontologies/PPD-OLT?p=classes&conceptid=https%3A%2F%2Fopendata.inrae.fr%2Fppd-res%2FoliveTree%23bbch_oliveTree_secondaryStage_BBCH00

Voir que l'API retourne bien 2 synonymes pour cette classe: 
https://data.stageportal.lirmm.fr/ontologies/PPD-OLT/classes/https%3A%2F%2Fopendata.inrae.fr%2Fppd-res%2FoliveTree%23bbch_oliveTree_secondaryStage_BBCH00?display=all

Pourtant l'UI n'en montre qu'un 
<img width="335" alt="Capture d’écran 2024-05-02 à 08 34 31" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/db85a4a3-a228-487b-99ee-f05026ccea7e">

La partie "Raw data" montre bien les 2. Idéalement il faudrait qu'ils soient sur des lignes différentes
<img width="558" alt="Capture d’écran 2024-05-02 à 08 35 12" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/18f2bee4-9bce-4250-9ef5-3dd559b719a8">

**Comment by Bilelkihal** [comment]
fixed in: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/613
