### ISSUE TITLE
Redirection vers nous-meme tant que possible dans la partie Raw data

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#610]
Il faut qu'on arrive a détecter re rediriger autant que possible vers le meme portail (nous-meme) les valeurs des propriétés dans la partie Raw Data. 

Example: 
Aller a https://stageportal.lirmm.fr/ontologies/PPD-OLT?p=classes&conceptid=https%3A%2F%2Fopendata.inrae.fr%2Fppd-res%2FoliveTree%23bbch_oliveTree_secondaryStage_BBCH00

<img width="576" alt="Capture d’écran 2024-05-02 à 09 02 13" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/d348b133-fb37-4e9b-b958-2f3a3103e8d3">

Ici il faut que : 
- relatedCrop => reste dans StagePortal et passe chez FCU
- rdf:type => reste dans StagePortal pour le type qui est dans PPDO et passe chez PPDO

**Comment by syphax-bouazzouni** [comment]
related to https://github.com/agroportal/project-management/issues/583

**Comment by Bilelkihal** [comment]
Migrate `label_ajax_controller.js` to turbo rails by using chips as turbo frames (@Bilelkihal)

**Comment by Bilelkihal** [comment]
We still have that bug of miss resolving URLs

https://github.com/user-attachments/assets/90adbda7-0dba-486a-b99f-a6cbc1ca202e

**Comment by jonquet** [comment]
Oui en effet les URI clicker dans la video sont des URIs externes donc les deux devrait : (i) s'ouvrir dans une autre fenetre quand je clique dessus et (ii) ne pas rester dans AgroPortal meme pour le 2eme (cadastral vocabulary). On ne doit rester dans le portail que si l'URI a était transformée en label et donc on sait qu'on va bien arriver a une page correpsondante dans AgroPortal.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/821
![image](https://github.com/user-attachments/assets/aad2ec5c-530e-4ab3-b230-d7f49ec30d62)
