### ISSUE TITLE
Using long texts in recommender throws error

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#612]
### Screenshots
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/68b7ad48-dfbd-4cdd-9aea-6ec1110ee3df)
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/34dc7c61-8807-4cb7-a6ef-52d756fee630)

**Comment by syphax-bouazzouni** [comment]
Fixed with https://github.com/ontoportal-lirmm/ontologies_api/pull/79 and https://github.com/ontoportal-lirmm/ncbo_ontology_recommender/pull/1
