### ISSUE TITLE
infinit loading, and UI issue in Rewrite rules 

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#615]
Contact support button doesn't work (keep infinit loading), and it's better to put it in the right corner
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/61744974/1304d90b-8e18-4694-ab47-bce912bca20b)

**Comment by imadbourouche** [comment]
Fixed in : https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/580 (still open)
