### ISSUE TITLE
Phrases explicatives pour l'UI

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#618]
**Groups & Categories** 
In AgroPortal, ontologies are organized in groups and tagged with categories. Typically, groups associate ontologies from the same project or organization for better identification of the provenance.  Whereas categories are about  subjects/topics and enable to classify ontologies. As of 2016, AgroPortal's categories were established in cooperation with FAO Agricultural Information Management Standards (AIMS). Groups and categories, along with other metadata, can be used on the “Browse” page of AgroPortal to filter out the list of ontologies.

**Slices**
Slices allow users to interact (both via API or UI) only with a subset of ontologies in AgroPortal. If browsing the slice, all the portal features will be restricted to the chosen subset, enabling users to focus on their specific use cases. On AgroPortal, slices and groups are synchronized, so every group has a corresponding slice displaying only the ontologies from that group.

**OntoPortal Alliance**
The OntoPortal Alliance (https://ontoportal.org/) is a consortium of research and infrastructure teams dedicated
to promoting the development of ontology repositories and semantic artefact catalogues based on the open, collaboratively developed OntoPortal software (https://github.com/ontoportal). Hereafter are the current public and open repositories built with the technology maintained by the Alliance.

**Comment by jonquet** [comment]
**OntoPortal Alliance** 

The OntoPortal Alliance (https://ontoportal.org) is a consortium of research and infrastructure teams dedicated
to promoting the development of ontology repositories and semantic artefact catalogues based on the open, collaboratively
developed OntoPortal software (https://github.com/ontoportal). Hereafter are the current public and open repositories built with the technology maintained by the Alliance.

**Comment by Bilelkihal** [comment]
For the Slices and the Alliance sur le portail sections yes, and Groupes et catégories we add them once we do the federated page of the groups and categories.

Since this PR https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/598 is not gonna be included in the next release, I will extract the code related to the new layout of the home page with these descriptive text for the ontoportal alliance section in a new PR.

**Comment by syphax-bouazzouni** [comment]
Done in #631
