### ISSUE TITLE
Specific color in the hierarchy tree to distinguish reused terms from the canonical ones (explicitly defined in the ontology)

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#62]
This feature request concenr the display o gthe heirarchy tree in AgroPortal / OntoPortal. 

The idea would be distinguish graphically the terms that are "reused" (i.e., declare in another namespace than the current ontology being display) from the canonical terms (i.e., the ones explicitly defined inside the ontologie and within the same namespace).

The following image is an example from [AGRO](http://agroportal.lirmm.fr/ontologies/AGRO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FAGRO_00000346)

![image](https://user-images.githubusercontent.com/7379183/153567861-510430e3-2721-421c-a590-135301ae8297.png)

The term highlighted is defined in AGRO (http://purl.obolibrary.org/obo/AGRO_00000346).
The term above in the hierarchy is defined in XCO (http://purl.obolibrary.org/obo/XCO_0000000)

AgroPortal highlights and puts in bold the term currently browsed. I would change this to only highlight it and keep the bold distinctions to display all terms in the hierarchy that are canonical i.e., defined explicitly by the ontology (not reused).

Related discussion about search results in https://github.com/ncbo/bioportal_web_ui/issues/101

**Comment by jonquet** [comment]
The best way to process (distinguish) seems to rely on a specific metadata property that tells us the pattern of the URIs for objects (classes, instances, properties) defined in this propoerty. 
For this we do have in AgroPortal the property `uriRegexPattern`

http://data.agroportal.lirmm.fr/ontologies/AGRO/latest_submission?display=uriRegexPattern

![image](https://user-images.githubusercontent.com/7379183/153569549-21193723-8cb4-442a-ab02-0c964293e20e.png)

**Comment by syphax-bouazzouni** [comment]
related to #293

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/650
