### ISSUE TITLE
Dans le message de diagnostic de resolution... changer URL par URI

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#626]
<img width="547" alt="Capture d’écran 2024-05-22 à 17 38 45" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/588cc35c-8178-44f4-b98a-40554c9baf5c">

**Comment by syphax-bouazzouni** [comment]
is this done @imadbourouche  ?

**Comment by imadbourouche** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/651
