### ISSUE TITLE
Putting  "Jean-Louis Janin" as an ontology creator return an errors 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#636]
### To reproduce 
* GO to LEXEAU and click on edit submission 
* GO to person and organization tabs
* in the creator input, search "Jean-Louis Janin" and click on it, we  see an error instead of the selected Agent 

![Attachment](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/acc60b1e-bb30-4811-971b-929e843c1531)

![Attachment-1](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/a69ac588-35ac-4d44-91aa-33c145ad2ccd)

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/645
