### ISSUE TITLE
Ontology selector in the group creation (maybe also categories) in the admin page do not use the right ontology selector

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#637]
<img width="314" alt="Capture d’écran 2024-05-29 à 11 31 11" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/3c2e3518-d6cf-467f-8cea-7cfc071a073f">

We can only select the ontologies by acronyms there, rather than by name. 
We do not need the "advanced selector"

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/641
