### ISSUE TITLE
Add pt-BR to the language selector in the UI and store the value ... 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#653]
Either witha fake URI : "http://lexvo.org/id/iso639-1/pt-BR"
Or with only the string "pt-BR" if the enforcedValues allow it.
<img width="495" alt="Capture d’écran 2024-06-05 à 16 40 07" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/6efcb6ea-1f2c-44a2-900d-91eeb0883797">

Name for this language should be "Brazilian"

Plus we would need a specific flag in the UI for t.

**Comment by syphax-bouazzouni** [comment]
add in the backend, the UI side discussion is moved to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/759
![image](https://github.com/user-attachments/assets/ab87d078-84b2-430e-ba1c-1571df74f9db)
