### ISSUE TITLE
We need to remove the subjet slot from the "Projects and usage information" section in Sumamry page

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#654]
<img width="446" alt="Capture d’écran 2024-06-05 à 15 44 55" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/027d801b-a205-43be-8ba5-569df6e9242e">

We do not need it anymore ... especially with URLs like this . 
Its already dispalyed in the "General information" sectopn

**Comment by syphax-bouazzouni** [comment]
Done in  https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/719
