### ISSUE TITLE
Add a direct link to AgroPortal project management GitHub issues in the footer

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#660]
I realise we would like "technical" requests/bugs to be reported as much as possible on GitHub here: 
https://github.com/agroportal/project-management/issues

But we do not even have a  direct link to this in AgroPortal. 

Proposition is to add it in the footer "Support" section with a title: "Issues and Requests" (en francais: Problèmes et demandes"

**Comment by Bilelkihal** [comment]
Done here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/665
