### ISSUE TITLE
3 different ratio left column / right column when browsing content

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#661]
Curently (since v2.8) we have 3 different ratio in the frame of the pages: 

Classes: 
<img width="395" alt="Capture d’écran 2024-06-07 à 06 44 46" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/b6e0d78d-9883-4472-b04b-6c8fe5a9f4ae">

Properties:
<img width="402" alt="Capture d’écran 2024-06-07 à 06 45 15" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/c15924b1-2343-4abf-92d2-f25527e7825f">

Instances:
<img width="399" alt="Capture d’écran 2024-06-07 à 06 45 54" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/36590716-8591-4222-ac80-1ec26fcf46ca">

This is confusing and not really nice.

**Comment by jonquet** [comment]
A noter que les colonnes de gauche des 2 derniers on un moyen permettant d'ecarter la largeur qui ne marche pas. Tandis que la colonne de la page Classes ne l'a pas. 
<img width="61" alt="Capture d’écran 2024-06-07 à 07 06 21" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/df0781d7-5ad4-4004-9d98-d99d90354917">

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/664
