### ISSUE TITLE
Probleme d'ouverture de page pour les objets skos qui ne sont pas des classes

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#667]
Objects in semantic ressources that are not directly mapped to a model (class, concept, property, individual, scheme, collection, skos-xl/Label) shall now open with the new tool "Search content"

To test/reproduce go to : 
https://agroportal.lirmm.fr/ontologies/ANAEETHES?p=classes&conceptid=http%3A%2F%2Fopendata.inra.fr%2FanaeeThes%2Fc2_2445
Raw data 
<img width="778" alt="Capture d’écran 2024-06-10 à 00 03 13" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/f558a5af-e955-4523-964b-f531f847bb5b">

Click on def link. 
<img width="1321" alt="Capture d’écran 2024-06-10 à 00 03 41" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/77447431-5fa1-49ee-a34c-b1f903bf4741">

**Comment by syphax-bouazzouni** [comment]
Fixed in  https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/821, now it redirects to the correct external link
![image](https://github.com/user-attachments/assets/b36b5e7b-eecc-4451-bdcf-a960232cde84)
