### ISSUE TITLE
Opening the link of a private ontology while being not logged in throws a 404 page

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#672]
### Issue description
When attempting to access a private ontology without being logged in, the user encounters a 404 error page. This behavior is confusing and non-informative. Instead, it would be more user-friendly to redirect unauthenticated users to the login page.

**Comment by syphax-bouazzouni** [comment]
duplicate of https://github.com/agroportal/project-management/issues/563
