### ISSUE TITLE
Landscape page error when logged in

### ISSUE THREAD

**Issue by galviset** [ontoportal-lirmm/bioportal_web_ui#675]
### Description
The Landscape page can be seen in the EarthPortal (2.8 release), however it throws a 404 error when trying to reach it when being logged in.
The role of the user and their whether they uploaded ontologies or not does not influence that.

### Traceback
```
F, [2024-06-14T13:04:07.978648 #24555] FATAL -- :   
NoMethodError (undefined method `start_with?' for #<OpenStruct:0x00007f035af94ef8>):
  
app/controllers/landscape_controller.rb:114:in `block (2 levels) in index'
app/controllers/landscape_controller.rb:111:in `each'
app/controllers/landscape_controller.rb:111:in `block in index'
app/controllers/landscape_controller.rb:105:in `each'
app/controllers/landscape_controller.rb:105:in `index'
```
Following this traceback, we hit these lines:
```
    # Iterate ontologies to get the submissions with all metadata
    @submissions.each do |sub|
```
So I decided to check if there was an invalid submission using ncbo_cron console. Turns out that there was an invalid ontology submission indeed.
The problem exposed here is that if there is a single invalid submission on the portal, the Landscape page will break when logged in.

### How to reproduce
Login on EarthPortal and navigate to the Landscape page when there is at least one invalid submission in the portal data.

**Comment by syphax-bouazzouni** [comment]
@galviset , the issue is in this line 
![image](https://github.com/user-attachments/assets/cc5f527e-e429-418c-b9aa-57b662c216f3)
It attended to get a string but received an object. This means that one of the submissions that are accessible only by an admin has a corrupted language value in the natural value. You should clean using the admin metadata curator or the ncbo cron console.

**Comment by galviset** [comment]
There are no more invalid submissions on the EarthPortal now, and despite some ontologies having incorrect values for natural languages (using other URIs than http://lexvo.org/id/iso639-1/ ), the landscape page now displays correctly.
