### ISSUE TITLE
Statistics page error

### ISSUE THREAD

**Issue by galviset** [ontoportal-lirmm/bioportal_web_ui#676]
### Description
The statistics page throw a 404 error unconditionally on the EarthPortal (freshly updated to 2.8).
Additionally, the Ontology number of the homepage shows 0:
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/44084050/6ad8b3a0-02d1-49d2-be4d-812702a38888)

### Traceback
```ruby
app/helpers/statistics_helper.rb:37:in `block in merge_time_evolution_data'
app/helpers/statistics_helper.rb:37:in `map'
app/helpers/statistics_helper.rb:37:in `merge_time_evolution_data'
app/controllers/statistics_controller.rb:10:in `index'
F, [2024-06-14T13:45:13.473564 #24555] FATAL -- :   
NoMethodError (undefined method `first' for nil:NilClass):
```

Possibly related to #675.

**Comment by galviset** [comment]
Some news on this one: it does not happens anymore when Google Analytics is properly configured. I'll leave up to you if this issue should be closed or not.

**Comment by syphax-bouazzouni** [comment]
Yes, this issue is related to Google Analytics, if not enabled this page and some others related to analytics don't work. 

@galviset , Did the documentation that I gave you for the Google Analytics, help you or you had to add  some changes to it ?
