### ISSUE TITLE
Mappings tab of a selected concept has column width issues

### ISSUE THREAD

**Issue by galviset** [ontoportal-lirmm/bioportal_web_ui#687]
The mapping tab that can be accessed by clicking on a concept in the tree can have some issues in the column width if the first column have wide content.

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/44084050/f16e89d7-ad69-41f4-ab83-a4016fea9ced)

Suggestion: Make the Edit and Delete button only as icons on top of each other instead of side by side should save some space.

**Comment by syphax-bouazzouni** [comment]
@galviset did you progress on this?

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/798
