### ISSUE TITLE
Properties and Instances tab need to have a subtab "Details" and a {} button on the right

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#706]
We need to harmonize the way we display Properties and Instances wrt how we display Classes
<img width="1051" alt="Capture d’écran 2024-07-04 à 15 24 47" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/a9b636a6-e545-48d5-93a5-298d7be416cf">

We need to adopt the same layout with Details as a 1st sub-tab (and no othger for the moment) and on the right the API cotextual button that open respectively the current property API call or current isntance API call

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/754
