### ISSUE TITLE
Missing maj to button save and cancel

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#707]
When someone edit a reply to a note 

<img width="289" alt="Capture d’écran 2024-07-04 à 15 36 32" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/7f53b288-4cf0-4bef-9737-43f49c79b4f2">

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/724
