### ISSUE TITLE
Adding other information related to a properties in the UI 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#708]
This issue is certainly a duplicate, but ti would help prioritize this. 

Go to https://agroportal.lirmm.fr/ontologies/C3POPARAM/maxValue
We do not see domain and range
Where as the source file contain them :
<img width="848" alt="Capture d’écran 2024-07-04 à 15 38 55" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/df624e8d-d5ea-4ef6-b36e-32c81783a9c9">

And they are in our triple store: 
<img width="664" alt="Capture d’écran 2024-07-04 à 15 39 43" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/e8e4769b-4962-4a6d-be1d-4a1564629699">

However there are not in the API: 
https://data.agroportal.lirmm.fr/ontologies/C3POPARAM/properties/http%3A%2F%2Fwww.elzeard.co%2Fontologies%2Fc3po%2Fparameter%23maxValue?display=all

So we need a backend change: 

- [x] https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/142

**Comment by syphax-bouazzouni** [comment]
fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/738
