### ISSUE TITLE
When activating "Ontology views" in the Search then the ontology selector should contain them 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#709]
<img width="1074" alt="Capture d’écran 2024-07-04 à 16 13 34" src="https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/7379183/f7e4956b-b426-4c24-80bc-fce4cb87227c">

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/784
