### ISSUE TITLE
L'URL contextuelle dans l'onglet property contient instanceid dedans

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#711]
Aller a https://agroportal.lirmm.fr/ontologies/AGRO

Puis passer sur l'onglet  Properties.
L'URL contextuelle générer est alors : 
https://agroportal.lirmm.fr/ontologies/AGRO?p=properties&instanceid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_01001572&propertyid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000118

**Comment by syphax-bouazzouni** [comment]
related to https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/715

**Comment by Bilelkihal** [comment]
Fixed in: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/723
