### ISSUE TITLE
We lose view of value on submssion creation or editition

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#714]
Use case https://agroportal.lirmm.fr/ontologies/PPD-OLT, which is a view of PPDO.

When we click on edit ontology we lose the value 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/d4d1c76a-d9dd-4c0b-8350-0790cd3e6eeb)

When we click on the new submission button we lost also the value 
![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/874be53f-e566-440b-9dfb-6fab62f0f58c)

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/720
