### ISSUE TITLE
?propoertid is added to the ontology summary page URL automaticly ?

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#715]
### To reproduce 
* Go to an ontology summary page, for example: https://agroportal.lirmm.fr/ontologies/PPD-OLT
* Wait 1s
* And you see in the URL `?propoertyid` added without any reason (the full URL  became https://agroportal.lirmm.fr/ontologies/PPD-OLT?propertyid=http://purl.org/dc/elements/1.1/author)

![image](https://github.com/ontoportal-lirmm/bioportal_web_ui/assets/29259906/e3547967-c7c5-4857-ae6f-19b1e3baf6e2)

**Comment by Bilelkihal** [comment]
Fixed in: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/723

**Comment by Bilelkihal** [comment]
fixed in: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/723
