### ISSUE TITLE
Remove the "Instances" tabs when browsing SKOS vocabularies

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#72]
When browsing SKOS vocabularies, everything is an instance. Therefore, the new "Instances" tabs create a bit of confusion. 

I suggest to remove them. 
- At the ontology level  
<img width="425" alt="image" src="https://user-images.githubusercontent.com/7379183/163495629-7d9dbecf-d1ff-483b-a3e2-9ecbdd389f89.png">

- At the concept level
<img width="178" alt="image" src="https://user-images.githubusercontent.com/7379183/163495579-2262323d-d615-4602-865a-a3f5756f7a3a.png">

(at the ontology level we already discussed to "replace" it by the "Scheme" tab

**Comment by syphax-bouazzouni** [comment]
Done
