### ISSUE TITLE
Changes "Classes" tab name to "Concepts" when browsing SKOS vocabularies

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#73]
Related to #72, as we are starting to develop "specific to SKOS interfaces" then I would suggest to do this change.

**Comment by jonquet** [comment]
The same for the sub tab : 
<img width="155" alt="image" src="https://user-images.githubusercontent.com/7379183/163597504-07d3a322-8008-4d70-8db5-82fc64cf0f07.png">

=> Change Class by Concept

**Comment by syphax-bouazzouni** [comment]
## Result 

![Image](https://user-images.githubusercontent.com/29259906/174103036-aef112d8-39be-4a5c-9907-baca0caa2111.png)

## Deployment

- [ ] Testportal
- [ ] Stageportal
- [ ] Bioportal
- [ ] Agroportal
