### ISSUE TITLE
O'FAIRe provoque une erreur sur une ontologie nouvelle 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#74]
On vient de charger SAREF4AGRI
D'apres moi c'est la première ontologie (pas soumission) nouvelle depuis la release de O'FAIRe dans AgroPortal. 

Il semblerait que cela crée un problème car la page Summary ne s'affiche pas. 
Le log expose le probleme suivant: 

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/7379183/164802630-b99da239-b014-474c-a918-8440b2b187d7.png">

**Comment by syphax-bouazzouni** [comment]
It seems it's not related to the FAIRness service, for testing, I created a new ontology (AGROVOC) in testportal and no errors have occurred.
Debugging will be continued by adding SAREF4AGRI in testportal

**Comment by syphax-bouazzouni** [comment]
a another use case, when the "ofaire services" is down it causes 



![Image](https://user-images.githubusercontent.com/29259906/179477315-35beb103-24bd-453b-acbd-106d231d1014.png)

**Comment by syphax-bouazzouni** [comment]
fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/fca7af65fdf32645e119dadb5401301c5d8ce0f5
