### ISSUE TITLE
Q&A Group and categories

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#741]
- [ ] quand on crée un categorie on reste sur le meme modal ouvert qui garde le bouton "Create category" ce qui fait un peu bizarre... et si on reclique le bouton on a une erreur vide

<img width="748" alt="Capture d’écran 2024-09-04 à 12 32 58" src="https://github.com/user-attachments/assets/6f0eb7d1-c6ff-43bc-bdfd-ffbe5bb1cde3">

- [x] Je suppose que la category "The category root" a été crée pour tester l'affichage quand la description est super longue. En effet il faut un acordeon. 

<img width="529" alt="Capture d’écran 2024-09-04 à 12 43 38" src="https://github.com/user-attachments/assets/eb2ba47f-9a29-4974-86d4-2695e8727ca6">

- [ ] pas forcément tres grave mais pour voir les effets de changements de categories sur la page: https://stageportal.lirmm.fr/categories il faut vider tous les caches... c'est un peu lourd. On pourrait supposer qu'a l"edition d'une catégorie cette page est regenerée dans le back ? 

- [x] Discuté, mais répété ici: mettre le mouse over sur le chip de l'acronyme de l'ontologie avec ouverture de l'ontologie si click

- [x] Changer la phrase "As of 2016, AgroPortal's categories were established in cooperation with FAO Agricultural Information Management Standards (AIMS)." par "As of 2016, AgroPortal's categories were established in cooperation with FAO AIMS. In 2024, we moved to UNESCO nomenclature for fields of science and technology."

- [x] Majuscule a Categories
<img width="284" alt="Capture d’écran 2024-09-04 à 12 57 34" src="https://github.com/user-attachments/assets/0ae7014b-3b2d-4c74-ab07-067b4bf409fe">

- [x] Ne pas oublier l'entrée "Groups and Categories" dans le menu Support en haut a droite.

- [ ] Sur la page summary d'une ontologie, les chip de Categories ne sont pas les memes: ils sont en minuscules. Idem pour le chip des groupes dans le menu "Community" mais la c'est plus comprehensible car on affiche le nom du groupe et pas l'acronyme
<img width="336" alt="Capture d’écran 2024-09-04 à 13 15 32" src="https://github.com/user-attachments/assets/932c9988-8ec9-442a-a2ba-22085fd1c767">

- [x] Penser au point (i) a coté du bouton. Dans les 2 minis textes  afficher: "See more information about Groups and Categories" avec lien sur "Group and Categories qui ouvre respectivement la page /categories ou /groups  
<img width="110" alt="Capture d’écran 2024-09-04 à 13 06 42" src="https://github.com/user-attachments/assets/d3ef6e39-af74-4f9e-83a3-7355ccb6f5b1">

- [x] Ajouter aussi la phrase "See more information about Groups and Categories" dans le mouse over du menu Community dans la page Summary. A noter que le message est faux pour ce menu d'ailleurs... c'est celui de méthode. Je propose de le rempalcer par "Metadata properties related to community information such as the code repository and issue tracker, the mailing list or the target audience. This includes also the Groups in AgroPortal. See more information about Groups and Categories."
<img width="553" alt="Capture d’écran 2024-09-04 à 13 20 51" src="https://github.com/user-attachments/assets/675999c1-3377-4f0a-be3b-68f04d6608ad">

- [ ] Quand on sélectionne un catégorie dans la page Browse (et dans le selector d'ontologies avancé) est-ce qu'on pourrait sélectioner automatiquement les sous categories d'une categories quand cette une catégeorie est actionnée? Sur l'exemple: HORTI est sous catégorie de AGRI. Cela permettrait de faire "une fausse fermeture transitive" qui sans que les ontologies aient été tagué 2 fois (avec AGRI et HORTI) permettrait tout de meme de sélectionner les ontologies HORTI (qui par inference devrait aussi etre taguée AGRI).
<img width="193" alt="Capture d’écran 2024-09-04 à 13 01 48" src="https://github.com/user-attachments/assets/871098cf-7fb5-4b51-b503-48b8abe3db10">

- [ ]  De manière similaire (mais inversée) dans la page d'edition de métadonnée et dans la page de création d'une ontologie, il faudrait que quand on sélectionne le chip d'une catégorie cela sélectionne automatiquement le chip de la parent categories (mais pas le contraire). Sur l'exemple, sélectionner HORTI devrait faire se sélectionner automatiquement AGRI. Et si je deselectionne HORTI, cela ne laisse AGRI que si un autre chip sélectionné l'a pour parent
<img width="1054" alt="Capture d’écran 2024-09-04 à 13 13 21" src="https://github.com/user-attachments/assets/a3f70089-412a-4a82-a5cc-544841664803">

**Comment by user34ngrau** [comment]
Q&A session - 5th of September (Anne Sophie, Nina)
Template of the answers : Number - [Title of the issue] : [Description of the issue] followed by an example : text and/ or screenshot and/or recording

1-  [Showing Groups] : [Sélection automatique, avec un affichage en vert, du nom du groupe sélectionné dans le bandeau "Groups" du "Filters]
Ex: AGBIODATA > click on "8 ontologies" > Results 7 ontologies mais dans "Filters" > "Groups" > "AGBIODATA" n'est pas automatiquement sélectionné

https://github.com/user-attachments/assets/b18a9bcf-e152-4782-9df4-4e81d563e271

2-   [Showing Categories] : [Sélection automatique, avec un affichage en vert, du nom de la catégories sélectionnée dans le bandeau "Categories" du "Filter]

3- [Orthographe] : [Mettre le mot "Ontologies" au singulier quand les valeurs < ou = 1] 
![Sans titre](https://github.com/user-attachments/assets/a7815642-d457-4fc6-a9d6-3c45763bd552)

4 - [Number of ontologies] : [Variation entre le nombre d'ontologies indiquées dans une catégorie dans la page "Groups and Categories" vs quand on click sur le nombre d'ontologie qui nous envoi sur la page "browse]
Ex GEO: In  "Groups and Categories" page > Category GEO has 2 ontologies : THESAGRO and CAT. However, when click on the "2 ontologies" button > only 1 is showing : THESAGRO whereas CAT ontology is on "no licence" so should appears

https://github.com/user-attachments/assets/8e274627-8ff3-4cb2-ac82-da11e7334eda
