### ISSUE TITLE
Q&A Property properties 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#742]
- [x] Sur la propriété suivante: https://stageportal.lirmm.fr/ontologies/AGROVOC?p=properties&propertyid=http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FaccrualMethod dans raw data, rangeIncludes n'a pas de namespace.

- [ ] Sur la même propriété j'ai l'impression dans Raw data qu'on duplique le rdfs:comment dans skos:definiton... ?? en tout cas quand on regarde l'export TTL (ou autre) on ne voit pas de propriété skos:definition. Ce problème est présent sur tout AGROVOC

- [x] Sur https://stageportal.lirmm.fr/ontologies/AGROVOC?p=properties&propertyid=http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FdateAccepted qui a des parents, on avait dit que comme pour les classes on affichait pas les parents car ils sont dans la hierachie sur le coté. 
<img width="478" alt="Capture d’écran 2024-09-04 à 13 43 32" src="https://github.com/user-attachments/assets/63cb8a6d-c44a-417a-b70a-18b1a2e90563">

- [x] Le details des propriétés devraient etre positionnés dans un bloc similaire au details des classes. Comme sur l'image mais sans Instance , Visu, Notes et Mappings mais par contre avec l'icone {} pour aller a l'appel correspondant.
<img width="645" alt="Capture d’écran 2024-09-04 à 16 07 12" src="https://github.com/user-attachments/assets/09a8a96c-3156-47b0-b615-a8af2df22af5">

- [ ] Pour cette propriété de RO: https://data.stageportal.lirmm.fr/ontologies/RO/properties/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000067
on a "mappé" 2 propriétés (rdfs:comment et obo_purl:IAO_0000115) a notre propriété "Definition" mais pour la propriété Accrual method dans AgROVO citée au dessus ... on ne l'a  pas fait pour la propriété dct:description
C'est assez bizarre.  

- [x] Cette propriété : https://agroportal.lirmm.fr/ontologies/ITAB?p=properties&propertyid=http%3A%2F%2Fwww.d2kab.org%2Fontologies%2Fephy%23dateFinUtilisation quand on demande l'export avec N-Triple et Turtle cela génère un internal server error

- [x] #743
<img width="667" alt="Capture d’écran 2024-09-04 à 16 33 36" src="https://github.com/user-attachments/assets/2c8d4270-762e-468e-8913-9d7eecb15f7f">
Elle n'existe pas dans OBOE...! 

- [ ] Voila les "links" pour la property suivante: https://data.stageportal.lirmm.fr/ontologies/OBOE/properties/http%3A%2F%2Fecoinformatics.org%2Foboe%2Foboe.1.2%2Foboe-core.owl%23ofEntity-
<img width="162" alt="Capture d’écran 2024-09-04 à 16 36 21" src="https://github.com/user-attachments/assets/b688fa68-eb8c-4563-be79-340f81600620">
En comparaison aux links des classes on a pas: instances, notes, mappings et ui (mais il y a submission en plus) => pour instance c'est normal, pour notes et mappings... c'est sans doute un autre Feature Request (a saisir: on devrait pouvoir avoir des notes et des mappings pour les proprietés aussi) mais ui, on devrait pouvoir assez facilement l'ajouter.

**Comment by syphax-bouazzouni** [comment]
>  Sur la propriété suivante: https://stageportal.lirmm.fr/ontologies/AGROVOC?p=properties&propertyid=http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FaccrualMethod dans raw data, rangeIncludes n'a pas de namespace.
C'est le comportement prévu, quand on arrive pas identifier le prefix, et en le survolant on voit l'URI en entier.

> Cette propriété : https://agroportal.lirmm.fr/ontologies/ITAB?p=properties&propertyid=http%3A%2F%2Fwww.d2kab.org%2Fontologies%2Fephy%23dateFinUtilisation quand on demande l'export avec N-Triple et Turtle cela génère un internal server error

Ce bug est connue est déjà fixer sur stage

**Comment by syphax-bouazzouni** [comment]
> Pour cette propriété de RO: https://data.stageportal.lirmm.fr/ontologies/RO/properties/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000067
on a "mappé" 2 propriétés (rdfs:comment et obo_purl:IAO_0000115) a notre propriété "Definition" mais pour la propriété Accrual method dans AgROVO citée au dessus ... on ne l'a pas fait pour la propriété dct:description
C'est assez bizarre.

Aucune logique est implementer pour prendre en compte aussi dct:description. 
 
Moved remaining to https://github.com/agroportal/project-management/issues/645 and https://github.com/agroportal/project-management/issues/646
