### ISSUE TITLE
Le lien du cookie banner Francais va vers la section "Privacy policy" des T&C en anglais 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#755]

**Comment by syphax-bouazzouni** [comment]
@muhammedBkf can you update our locale files and code to have in the footer the Privacy policy link point to: 

- when English to https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-conditions-naDsDo2Zxq#h-privacy-policy
- when French to https://doc.jonquetlab.lirmm.fr/share/e6158eda-c109-4385-852c-51a42de9a412/doc/terms-conditions-naDsDo2Zxq#h-vie-privee

The same idea for the other links Terms and conditions and Legal notices
![image](https://github.com/user-attachments/assets/a23973ce-7fc6-45c3-88d6-57a61262bb65)

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/760
