### ISSUE TITLE
After release 2.10.0 the concept tree does no more show active selected element

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#758]
See screencast bellow

https://github.com/user-attachments/assets/6e59a081-955d-4009-af51-19012f7d8bef

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni I can't reproduce this bug

**Comment by syphax-bouazzouni** [comment]
> @syphax-bouazzouni I can't reproduce this bug

I can't reproduce it too, so I close for now
