### ISSUE TITLE
Brazilian language support

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#759]
Related issue: https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/653

We have a couple of issues with this support.

The "pt-br" language does not exist in ISO639-1 (or even 3). So the recommendation is to use "pt-BR" which is a concaténation of the ISO639-1 code with the country code in another ISO. 
I wonder if this is could be one reason for the follwoing issues... 
But in theory, I would have put at enforced values ""http://lexvo.org/id/iso639-1/pt-br": "Brazilian" in https://data.agroportal.lirmm.fr/submission_metadata as this is what we recommend people to use in their source file. 

Then, I just did add "Brazilian" as a natural language for THESAGRO, but event with emptying all the possible caches, I could get ti see it in the language selector. 
<img width="142" alt="Capture d’écran 2024-09-27 à 10 14 08" src="https://github.com/user-attachments/assets/ce8a14e5-a3a3-4bf5-bad7-11ea5afa7203">
We need to reverify/consolidate this workflow: (i) an admin browse his/her ontology in AgroPortal; (ii) decide to add a natural langage (either via edit or via the shortcut in menu); (iii) go back to the Browsing and the menu MUST show the new langage. 

Note that the edition of the property does fire another parsing of the ontology but even afterward, not trace of the new language in the selector. This was experienced on both VOCGEO and THESAGRO.

**Comment by jonquet** [comment]
Possibly, all the languages "not in ISO-639-1" but of interest for us are here: https://www.andiamo.co.uk/resources/iso-language-codes/

**Comment by jonquet** [comment]
Guys, I am moving up the priority for this. Our collaborator at EMBRAPA are now up and ready to release THESAGRO and VOCGEO publicly (we are working on this since April) and we only need this.

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/766
