### ISSUE TITLE
fix the browse page white page loading bug 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#761]
See bellow screencast 

https://github.com/user-attachments/assets/93c52047-c5c1-4283-a986-82a0c845743c

**Comment by Bilelkihal** [comment]
@syphax-bouazzouni 
The bug is introduced in this commit: https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/76479295444d05ea952758c111804fecc72175e2
I'll investigate why this is happening and fix it

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/774
