### ISSUE TITLE
Slices statistics (other than the number of ontologies) need to concern only the ontologies within the Slice

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#762]
Lorsque l'on est sur une Slice le noombre d'ontologies ets bien "adapté" à la Slice mais pas les autres statistiques: 

Main AgroPortal 
<img width="877" alt="Capture d’écran 2024-09-29 à 22 14 51" src="https://github.com/user-attachments/assets/65d09063-696f-46c3-bd24-dd225005c18f">

Slice Crop
<img width="680" alt="Capture d’écran 2024-09-29 à 22 15 14" src="https://github.com/user-attachments/assets/16a65da7-3db5-424e-b7bf-08a842f2451c">

Il faudrait que les autres stats (sauf nombre d'utilisateurs) soient calculés également avec SEULEMENT les ontologies de la slice.

**Comment by syphax-bouazzouni** [comment]
Done  in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/775
