### ISSUE TITLE
AGROVOC classes tab is not working

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#78]
# Issue
We have an UI issue
http://agroportal.lirmm.fr/ontologies/AGROVOC/?p=classes&conceptid=root
![image](https://user-images.githubusercontent.com/29259906/169666011-da4c65ca-5f10-4c29-9ca3-b99f7440ce7c.png)

# Diagnostics
AGROV has no roots http://data.agroportal.lirmm.fr/ontologies/AGROVOC/classes/roots (@jonquet )
<img width="582" alt="image" src="https://user-images.githubusercontent.com/29259906/169665815-8944844b-96ac-48c1-baa0-6e581ed393dc.png">

# TODO

- [ ] Print the "missing roots" error log for the users 
- [ ] Fix the original resource to see if it implements our guide lines

**Comment by jonquet** [comment]
Have you verify this in the source file ? 
I don't see why AGROVOC that had (quite) always parsed right in AgroPortal would now not parse any more... I don't think the developper have remove roots (topLevelConcept).

**Comment by jonquet** [comment]
Seems skos:topConceptOf statements are still there : 

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/7379183/169898657-2e8c79f2-a4ac-418a-be2c-0d6931fafb91.png">

**Comment by jonquet** [comment]
Where is that log (mentioning ontolobridge) is from ?

**Comment by syphax-bouazzouni** [comment]
It is the property **skos:hasTopConcept** that is used to fetch the roots and not skos:topConceptOf.

I looked up  with the parsed version of agrovoc [owlapi.xrdf](http://data.agroportal.lirmm.fr/ontologies/AGROVOC/download?apikey=3aea6996-bb79-44c9-93c6-b2cef64f5f66&download_format=rdf) (the latest uploaded in the 20/05/2022), **and i didn't found any usage of the **skos:hasTopConcept** property**  
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/29259906/169905224-f9a2fa3a-2036-4cdb-b064-e53a1f12f0ba.png">

**Comment by jonquet** [comment]
#286 has been done
Then I have updated submission number 25. Waiting for processing tonight.

**Comment by syphax-bouazzouni** [comment]
Fixed by https://github.com/agroportal/project-management/issues/280
<img width="2372" alt="image" src="https://user-images.githubusercontent.com/29259906/183025754-4ec62ed9-6518-46d8-ba3a-7d0c6628ac56.png">
