### ISSUE TITLE
Hardcoded portal name in the new groups and  categories page 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#788]
https://stageportal.lirmm.fr/taxonomy
![image](https://github.com/user-attachments/assets/4eaa3f31-1496-46aa-967a-bf98dfd89bc6)

**Comment by jonquet** [comment]
A retoucher cette phrase en profiter pour changer "In 2024, we moved to UNESCO nomenclature for fields of science and technology"
Vers 
In 2024, we moved to UNESCO Thesaurus (https://vocabularies.unesco.org).

**Comment by Bilelkihal** [comment]
Done here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/850
