### ISSUE TITLE
Export in turtle and ntriples does not work in Agroportal  but deos in StagePortal ? 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#804]
Example https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes

![image](https://github.com/user-attachments/assets/267ab8e6-127a-4722-b9b1-7cb285fd03c2)

**Comment by jonquet** [comment]
Seems to work now on AgroPortal: https://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_6211
