### ISSUE TITLE
`Federated browse` Incorrect Results Count Display

### ISSUE THREAD

**Issue by Bilelkihal** [ontoportal-lirmm/bioportal_web_ui#859]
`Source:` https://docs.google.com/spreadsheets/d/1ccpt2GBtOje6PpWprcs-McLXq7IrCCz2Xt5Y4yLXYqE/edit?gid=1657118515#gid=1657118515

> this request : [https://stageportal.lirmm.fr/ontologies?search=actris&sort_by=ontology_name&portals=ecoportal%2Cearthportal](https://www.google.com/url?q=https://stageportal.lirmm.fr/ontologies?search%3Dactris%26sort_by%3Dontology_name%26portals%3Decoportal%252Cearthportal&sa=D&source=editors&ust=1732224333614459&usg=AOvVaw3VVlZTirBfgvpRvyW76j9b) shows results from Eco and Earth (same result) but it is written 0 for EarthPortal

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/94f243d7-0f77-4c67-a865-26fea326a6ad">

**Comment by Bilelkihal** [comment]
Deployed to stage

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/870
