### ISSUE TITLE
Downloading ontologies from the interface does not work for some ontologies

### ISSUE THREAD

**Issue by imadbourouche** [ontoportal-lirmm/bioportal_web_ui#861]
### Description
When you go to the summary page of an onology and try to download it, it does not work for some ontologies like: ANAEETHES, SFWO, TO ...etc, despite that the link will work when copy and paste it on new tab. 

- ANAEETHES ontology: https://agroportal.lirmm.fr/ontologies/ANAEETHES
- link of download button (the api) works correctly when copy/paste in new tab: http://data.agroportal.lirmm.fr/ontologies/ANAEETHES/download?apikey=1de0a270-29c5-4dda-b043-7c3580628cd5

https://github.com/user-attachments/assets/22450b4c-f86c-49c8-9609-64e1e3de9a98

**Comment by syphax-bouazzouni** [comment]
it does work for me

**Comment by imadbourouche** [comment]
> it does work for me

what are you using as browser?, I'm using google chrome and it's not working for me. I test it on firefox and it works fine.

**Comment by syphax-bouazzouni** [comment]
Firefox

**Comment by imadbourouche** [comment]
> Firefox

Yes it works in Firefox, but i'll test it with others and i'll test in other browsers to see what's wrong

**Comment by syphax-bouazzouni** [comment]
Yeah it do not work in Chrome,

**Comment by syphax-bouazzouni** [comment]
Critical one also @Bilelkihal

**Comment by imadbourouche** [comment]
The problem is the download URL is http version not https, and google chrome blocks downloads from http website and mark them as insecure. 

![insecure_downloading](https://github.com/user-attachments/assets/34590e90-f8c4-443b-989b-89fb7c44aed3)


We need to change the download url to https version 

![download_url_http](https://github.com/user-attachments/assets/f94271bc-0d6e-4538-8887-d1e9adf32e23)

**Comment by syphax-bouazzouni** [comment]
> Did a script that changes the metadata called dumpData. Now all the ontologies has an https download URL (dumpData). Test download the ontology from the interface: https://agroportal.lirmm.fr/ontologies/ANAEETHES

Assume fixed for now.
