### ISSUE TITLE
When federation enabled we should display only the top level categories (that does not have parent)

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#862]
Feedback from the ontoportal federation meeting 22/11/24, from biodivportal, earthportal

**Comment by jonquet** [comment]
Just to complete: 
- All the categories from the local portal 
- Top categories from the federated ones

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/877 and https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/6fb4988ac947f5663d038941d0774d9d9c960c3b
