### ISSUE TITLE
Add option to disable the twitter section 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#864]
Source Q/A 11/24

- Bilel: I see the message "Nothing to see here - yet" and I think it's because I'm not logged in to X on my browser, do we keep this section like this or what we should do exactly?

- Christelle  propose to delete this box. Out Elon Musk ;-)

- Parham: The box is there, but the posts has not fetched.

**Comment by Bilelkihal** [comment]
Possibilities to replace it:
- Groups/categories || projects

**Comment by syphax-bouazzouni** [comment]
See @imadbourouche https://github.com/biodivportal/ontoportal_web_ui/commit/526f8112214945615e0bb51726b964d71046cd1f#diff-1211700308b42367a41d399ab0cf8871eb97bf17664a4da78d578613f54edceaR170

**Comment by syphax-bouazzouni** [comment]
Done in https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/880
