### ISSUE TITLE
cagtegories page not working in StagePortal 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#866]
https://stageportal.lirmm.fr/categories

**Comment by Bilelkihal** [comment]
fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/858 and deployed to stage,
It was about some categories that are removed but still used as parent category for certain other categories.

**Comment by syphax-bouazzouni** [comment]
Is this not a bigger issue where, when we delete a category, we also need to delete its references as parent of child?

**Comment by syphax-bouazzouni** [comment]
It was done for the relation categories <->ontologies, here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/254/files#diff-1677c16da6a7f15bfb619547bcab5ddce1eb422fe4b8b96a971bb2cdafc47c99R27, so it need to be done also for the relation categories <->categories

**Comment by Bilelkihal** [comment]
Currently, when a category is associated with some ontologies, then we disable the delete button in the admin page: 
![image](https://github.com/user-attachments/assets/85fbc10b-8302-487f-9168-5a090e44cfb6)

And it's easy here to deal with if you want to delete the category anyway, you click on edit, you empty the ontologies list and then you delete.

But with parentCategories, you need to remove the category everywhere where it appears as a parentCategory and you can't have an idea who are those categories who are mentioning this category.

**Comment by syphax-bouazzouni** [comment]
@jonquet what is your opinion on this ?

**Comment by jonquet** [comment]
>But with parentCategories, you need to remove the category everywhere where it appears as a parentCategory and you can't have an idea who are those categories who are mentioning this category.
=>Unless you use the UI Category page. 

That sounds reasonable that to delete a category one verify that it's not referenced as a parent category somewhere.

**Comment by Bilelkihal** [comment]
> > But with parentCategories, you need to remove the category everywhere where it appears as a parentCategory and you can't have an idea who are those categories who are mentioning this category.
> > =>Unless you use the UI Category page.
> 
> That sounds reasonable that to delete a category one verify that it's not referenced as a parent category somewhere.

Done here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/876
