### ISSUE TITLE
federated search  result are not correct or merged 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#868]
Source Q/A 11/24
Christele: suggestion to merge the results when they are the same. Exemple of temperature in INRAETHES from stage and Agroportal. (2 distincts results). Test done : [https://stageportal.lirmm.fr/search?q=temperature&lang=en&portals%5B%5D=agroportal&portals%5B%5D=earthportal](https://www.google.com/url?q=https://stageportal.lirmm.fr/search?q%3Dtemperature%26lang%3Den%26portals%255B%255D%3Dagroportal%26portals%255B%255D%3Dearthportal&sa=D&source=editors&ust=1732278893508863&usg=AOvVaw01Y6b1zTPCj98NqnFOVHaV). Performance not efficient in stage portal for this request
Christelle: this request : [https://stageportal.lirmm.fr/ontologies?search=actris&sort_by=ontology_name&portals=ecoportal%2Cearthportal](https://www.google.com/url?q=https://stageportal.lirmm.fr/ontologies?search%3Dactris%26sort_by%3Dontology_name%26portals%3Decoportal%252Cearthportal&sa=D&source=editors&ust=1732278893514821&usg=AOvVaw2Fq6WPqdKaurZiIfhxGaYX) shows results from Eco and Earth (same result) but it is written 0 for EarthPortal
Syphax:  @Bilelkihal , this is a critical issue, you can see the the result that the temperature are merged together in stageportal and agroporal, even if they have the same URI and ontology.

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/872
