### ISSUE TITLE
Custom set ontologies does no more work

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#88]
### Use case (LEXEAU)

if a user a has set in his account settings page, LEXEAU as its custom ontology set he will no more be able to access it

**Comment by jonquet** [comment]
Ajouter des ontologies dans son custom set ne marche pas non plus.

**Comment by Bilelkihal** [comment]
Fixed here: https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/685
