### ISSUE TITLE
Probleme de largeur de la page Browse avec le formulaire de recherche 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#94]
Quand on utilise le formulaire de recherche sur la page Browse et qu'aucune ontologie ne match alors la largeur de la page est raccourci. Voir image 

<img width="920" alt="image" src="https://user-images.githubusercontent.com/7379183/196903186-d6746f9b-f5ef-4c01-bf7e-608519643fa1.png">

**Comment by syphax-bouazzouni** [comment]
fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/pull/119, thanks to @Bilelkihal 
Will be merged into production in the next release
