### ISSUE TITLE
Le captcha de SIFR BioPortal n'est plus a jour et empêche la creation de nouveau compte.

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#95]
Reporté par un utilisateur 

_J'ai essayé de créer un compte dans SIFR Bioportal (page http://bioportal.lirmm.fr/accounts/new), mais une erreur au niveau du captcha m'en empêche (message : Erreur pour le propriétaire du site: Domaine non valide pour la clé du site).
Pour la même raison, je n’ai pas non plus pu utiliser le formulaire de contact du site._

<img width="773" alt="image" src="https://user-images.githubusercontent.com/7379183/196906147-401a57f7-3efe-4bab-b7b1-25177322d511.png">

**Comment by syphax-bouazzouni** [comment]
The original issue is https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/96

**Comment by syphax-bouazzouni** [comment]
A temporary fix was done with https://gite.lirmm.fr/jonquetlab/bioportal-configs/-/commit/3ec469eafb43b18aa2e179db946586f645dbfe56



![Image](https://user-images.githubusercontent.com/29259906/196967602-728c9ea1-39af-40ad-8128-0829ad00871a.png)
