### ISSUE TITLE
update our configuration file to rails credentials

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal-lirmm/bioportal_web_ui#96]
Since last May and the [release v6.8.0](https://github.com/ncbo/bioportal_web_ui/releases/tag/v6.8.0) of the UI, NCBO (Stanford) started using encrypted configuration files (see https://github.com/ncbo/bioportal_web_ui/issues/200)

The main goal of this is to have the configuration file directly in the code repo, but encrypted so that only the developers possessing the to decrypt could read it.

In our (local) case, it means

- [ ] removing the configurations file from our private configuration repository and putting them in this repo. 
- [ ] change how our environment works, by adding agroportal and bioportal environments, for now, we have only the appliance environment representing both (see https://github.com/ontoportal-lirmm/bioportal_web_ui/tree/master/config/environments)
- [ ] Put the keys to decrypt those files in our private configuration repository.
- [ ] Change how our deployment scripts work.

**Comment by jonquet** [comment]
I would backlog this for the moment and wait for the next round of infrastructure update on our side AgroPortal/SIFR BioPortal. Eventually we will need to get rid of the local Git repo where config files are hosted.

**Comment by syphax-bouazzouni** [comment]
Will not do that as more complex, with no big benefits.
