### ISSUE TITLE
La mise a jour d'une ontologie (pas la soumission) ne change pas de page 

### ISSUE THREAD

**Issue by jonquet** [ontoportal-lirmm/bioportal_web_ui#97]
Quand on mets a jour une ontologie via la vue : Edit Ontology Information et qu'on valide les changements en appuyant sur le bouton "Save Ontology" la vue ne change pas. On reste coincé la et on re revient pas vers la vue Summary. Le bouton Save n'est plus clickable. 
En vérifiant via l'API, la modification semble bien effective dans le back end par contre. 

Le bouton précédent nous ramène bien sur a page Summary et les changements sont faits.

**Comment by syphax-bouazzouni** [comment]
origin https://github.com/ncbo/ontologies_api_ruby_client/pull/13

**Comment by syphax-bouazzouni** [comment]
fixed with https://github.com/ontoportal-lirmm/bioportal_web_ui/commit/e764fe91ba1aca02c1adcff5ffeaec60a658ac06
